// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cc/arduino/cli/commands/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This file is part of arduino-cli.
//
// Copyright 2024 ARDUINO SA (https://www.arduino.cc/)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_Instance: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of the instance.
  var id: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_DownloadProgress: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_DownloadProgress.OneOf_Message? = nil

  /// Sent when a download is started.
  var start: Cc_Arduino_Cli_Commands_V1_DownloadProgressStart {
    get {
      if case .start(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_DownloadProgressStart()
    }
    set {message = .start(newValue)}
  }

  /// Progress updates for a download.
  var update: Cc_Arduino_Cli_Commands_V1_DownloadProgressUpdate {
    get {
      if case .update(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_DownloadProgressUpdate()
    }
    set {message = .update(newValue)}
  }

  /// Sent when a download is finished or failed.
  var end: Cc_Arduino_Cli_Commands_V1_DownloadProgressEnd {
    get {
      if case .end(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_DownloadProgressEnd()
    }
    set {message = .end(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// Sent when a download is started.
    case start(Cc_Arduino_Cli_Commands_V1_DownloadProgressStart)
    /// Progress updates for a download.
    case update(Cc_Arduino_Cli_Commands_V1_DownloadProgressUpdate)
    /// Sent when a download is finished or failed.
    case end(Cc_Arduino_Cli_Commands_V1_DownloadProgressEnd)

  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_DownloadProgressStart: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// URL of the download.
  var url: String = String()

  /// The label to display on the progress bar.
  var label: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_DownloadProgressUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Size of the downloaded portion of the file.
  var downloaded: Int64 = 0

  /// Total size of the file being downloaded.
  var totalSize: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_DownloadProgressEnd: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// True if the download is successful.
  var success: Bool = false

  /// Info or error message, depending on the value of 'success'. Some examples:
  /// "File xxx already downloaded" or "Connection timeout".
  var message: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_TaskProgress: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Description of the task.
  var name: String = String()

  /// Additional information about the task.
  var message: String = String()

  /// Whether the task is complete.
  var completed: Bool = false

  /// Amount in percent of the task completion (optional).
  var percent: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_Programmer: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Platform name.
  var platform: String = String()

  /// Programmer ID.
  var id: String = String()

  /// Programmer name.
  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// MissingProgrammerError is a status error detail that is returned when
/// the operation can not be completed due to a missing programmer argument.
nonisolated struct Cc_Arduino_Cli_Commands_V1_MissingProgrammerError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Platform is a structure containing all the information about a single
/// platform release.
nonisolated struct Cc_Arduino_Cli_Commands_V1_Platform: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Generic information about a platform.
  var metadata: Cc_Arduino_Cli_Commands_V1_PlatformMetadata {
    get {_metadata ?? Cc_Arduino_Cli_Commands_V1_PlatformMetadata()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  var hasMetadata: Bool {self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  mutating func clearMetadata() {self._metadata = nil}

  /// Information about a specific release of a platform.
  var release: Cc_Arduino_Cli_Commands_V1_PlatformRelease {
    get {_release ?? Cc_Arduino_Cli_Commands_V1_PlatformRelease()}
    set {_release = newValue}
  }
  /// Returns true if `release` has been explicitly set.
  var hasRelease: Bool {self._release != nil}
  /// Clears the value of `release`. Subsequent reads from it will return its default value.
  mutating func clearRelease() {self._release = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _metadata: Cc_Arduino_Cli_Commands_V1_PlatformMetadata? = nil
  fileprivate var _release: Cc_Arduino_Cli_Commands_V1_PlatformRelease? = nil
}

/// PlatformSummary is a structure containing all the information about
/// a platform and all its available releases.
nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformSummary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Generic information about a platform.
  var metadata: Cc_Arduino_Cli_Commands_V1_PlatformMetadata {
    get {_metadata ?? Cc_Arduino_Cli_Commands_V1_PlatformMetadata()}
    set {_metadata = newValue}
  }
  /// Returns true if `metadata` has been explicitly set.
  var hasMetadata: Bool {self._metadata != nil}
  /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
  mutating func clearMetadata() {self._metadata = nil}

  /// Maps version to the corresponding PlatformRelease.
  var releases: Dictionary<String,Cc_Arduino_Cli_Commands_V1_PlatformRelease> = [:]

  /// The installed version of the platform, or empty string if none installed.
  var installedVersion: String = String()

  /// The latest available version of the platform that can be installable, or
  /// empty if none available.
  var latestVersion: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _metadata: Cc_Arduino_Cli_Commands_V1_PlatformMetadata? = nil
}

/// PlatformMetadata contains generic information about a platform (not
/// correlated to a specific release).
nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Platform ID (e.g., `arduino:avr`).
  var id: String = String()

  /// Maintainer of the platform's package.
  var maintainer: String = String()

  /// A URL provided by the author of the platform's package, intended to point
  /// to their website.
  var website: String = String()

  /// Email of the maintainer of the platform's package.
  var email: String = String()

  /// If true this Platform has been installed manually in the user' sketchbook
  /// hardware folder.
  var manuallyInstalled: Bool = false

  /// True if the latest release of this Platform has been deprecated.
  var deprecated: Bool = false

  /// If true the platform is indexed.
  var indexed: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// PlatformRelease contains information about a specific release of a platform.
nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformRelease: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name used to identify the platform to humans (e.g., "Arduino AVR Boards").
  var name: String = String()

  /// Version of the platform release.
  var version: String = String()

  /// Type of the platform.
  var types: [String] = []

  /// True if the platform is installed.
  var installed: Bool = false

  /// List of boards provided by the platform. If the platform is installed,
  /// this is the boards listed in the platform's boards.txt. If the platform is
  /// not installed, this is an arbitrary list of board names provided by the
  /// platform author for display and may not match boards.txt.
  var boards: [Cc_Arduino_Cli_Commands_V1_Board] = []

  /// A URL provided by the author of the platform's package, intended to point
  /// to their online help service.
  var help: Cc_Arduino_Cli_Commands_V1_HelpResources {
    get {_help ?? Cc_Arduino_Cli_Commands_V1_HelpResources()}
    set {_help = newValue}
  }
  /// Returns true if `help` has been explicitly set.
  var hasHelp: Bool {self._help != nil}
  /// Clears the value of `help`. Subsequent reads from it will return its default value.
  mutating func clearHelp() {self._help = nil}

  /// This field is true if the platform is missing installation metadata (this
  /// happens if the platform has been installed with the legacy Arduino IDE
  /// <=1.8.x). If the platform miss metadata and it's not indexed through a
  /// package index, it may fail to work correctly in some circumstances, and it
  /// may need to be reinstalled. This should be evaluated only when the
  /// PlatformRelease is `Installed` otherwise is an undefined behaviour.
  var missingMetadata: Bool = false

  /// True this release is deprecated.
  var deprecated: Bool = false

  /// True if the platform dependencies are available for the current OS/ARCH.
  /// This also means that the platform is installable.
  var compatible: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _help: Cc_Arduino_Cli_Commands_V1_HelpResources? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Platform ID (e.g., `arduino:avr`).
  var id: String = String()

  /// Version of the platform.
  var version: String = String()

  /// Installation directory of the platform.
  var installDir: String = String()

  /// 3rd party platform URL.
  var packageURL: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_Board: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name used to identify the board to humans.
  var name: String = String()

  /// Fully qualified board name used to identify the board to machines. The FQBN
  /// is only available for installed boards.
  var fqbn: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_HelpResources: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A URL provided by the author of the platform's package, intended to point
  /// to their online help service.
  var online: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_Sketch: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Absolute path to a main sketch files.
  var mainFile: String {
    get {_storage._mainFile}
    set {_uniqueStorage()._mainFile = newValue}
  }

  /// Absolute path to folder that contains main_file.
  var locationPath: String {
    get {_storage._locationPath}
    set {_uniqueStorage()._locationPath = newValue}
  }

  /// List of absolute paths to other sketch files.
  var otherSketchFiles: [String] {
    get {_storage._otherSketchFiles}
    set {_uniqueStorage()._otherSketchFiles = newValue}
  }

  /// List of absolute paths to additional sketch files.
  var additionalFiles: [String] {
    get {_storage._additionalFiles}
    set {_uniqueStorage()._additionalFiles = newValue}
  }

  /// List of absolute paths to supported files in the sketch root folder, main
  /// file excluded.
  var rootFolderFiles: [String] {
    get {_storage._rootFolderFiles}
    set {_uniqueStorage()._rootFolderFiles = newValue}
  }

  /// Default FQBN set in project file (sketch.yaml).
  var defaultFqbn: String {
    get {_storage._defaultFqbn}
    set {_uniqueStorage()._defaultFqbn = newValue}
  }

  /// Default Port set in project file (sketch.yaml).
  var defaultPort: String {
    get {_storage._defaultPort}
    set {_uniqueStorage()._defaultPort = newValue}
  }

  /// Default Protocol set in project file (sketch.yaml).
  var defaultProtocol: String {
    get {_storage._defaultProtocol}
    set {_uniqueStorage()._defaultProtocol = newValue}
  }

  /// List of profiles present in the project file (sketch.yaml).
  var profiles: [Cc_Arduino_Cli_Commands_V1_SketchProfile] {
    get {_storage._profiles}
    set {_uniqueStorage()._profiles = newValue}
  }

  /// Default profile set in the project file (sketch.yaml).
  var defaultProfile: Cc_Arduino_Cli_Commands_V1_SketchProfile {
    get {_storage._defaultProfile ?? Cc_Arduino_Cli_Commands_V1_SketchProfile()}
    set {_uniqueStorage()._defaultProfile = newValue}
  }
  /// Returns true if `defaultProfile` has been explicitly set.
  var hasDefaultProfile: Bool {_storage._defaultProfile != nil}
  /// Clears the value of `defaultProfile`. Subsequent reads from it will return its default value.
  mutating func clearDefaultProfile() {_uniqueStorage()._defaultProfile = nil}

  /// Default Programmer set in project file (sketch.yaml).
  var defaultProgrammer: String {
    get {_storage._defaultProgrammer}
    set {_uniqueStorage()._defaultProgrammer = newValue}
  }

  /// Default Port configuration set in project file (sketch.yaml).
  var defaultPortConfig: Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration {
    get {_storage._defaultPortConfig ?? Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration()}
    set {_uniqueStorage()._defaultPortConfig = newValue}
  }
  /// Returns true if `defaultPortConfig` has been explicitly set.
  var hasDefaultPortConfig: Bool {_storage._defaultPortConfig != nil}
  /// Clears the value of `defaultPortConfig`. Subsequent reads from it will return its default value.
  mutating func clearDefaultPortConfig() {_uniqueStorage()._defaultPortConfig = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The port configuration parameters.
  var settings: [Cc_Arduino_Cli_Commands_V1_MonitorPortSetting] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_MonitorPortSetting: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The setting identifier.
  var settingID: String = String()

  /// The setting value.
  var value: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SketchProfile: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the profile.
  var name: String = String()

  /// FQBN used by the profile.
  var fqbn: String = String()

  /// Programmer used by the profile.
  var programmer: String = String()

  /// Default Port in this profile.
  var port: String = String()

  /// Default Port configuration set in project file (sketch.yaml).
  var portConfig: Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration {
    get {_portConfig ?? Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration()}
    set {_portConfig = newValue}
  }
  /// Returns true if `portConfig` has been explicitly set.
  var hasPortConfig: Bool {self._portConfig != nil}
  /// Clears the value of `portConfig`. Subsequent reads from it will return its default value.
  mutating func clearPortConfig() {self._portConfig = nil}

  /// Default Protocol in this profile.
  var `protocol`: String = String()

  /// Platforms used by the profile.
  var platforms: [Cc_Arduino_Cli_Commands_V1_ProfilePlatformReference] = []

  /// Libraries used by the profile.
  var libraries: [Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _portConfig: Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ProfilePlatformReference: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Platform ID (e.g., `arduino:avr`).
  var id: String = String()

  /// Version of the platform.
  var version: String {
    get {_version ?? String()}
    set {_version = newValue}
  }
  /// Returns true if `version` has been explicitly set.
  var hasVersion: Bool {self._version != nil}
  /// Clears the value of `version`. Subsequent reads from it will return its default value.
  mutating func clearVersion() {self._version = nil}

  /// 3rd party platform URL.
  var indexURL: String {
    get {_indexURL ?? String()}
    set {_indexURL = newValue}
  }
  /// Returns true if `indexURL` has been explicitly set.
  var hasIndexURL: Bool {self._indexURL != nil}
  /// Clears the value of `indexURL`. Subsequent reads from it will return its default value.
  mutating func clearIndexURL() {self._indexURL = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _version: String? = nil
  fileprivate var _indexURL: String? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var library: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.OneOf_Library? = nil

  /// The library is installed from the Library Index.
  var indexLibrary: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.IndexLibrary {
    get {
      if case .indexLibrary(let v)? = library {return v}
      return Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.IndexLibrary()
    }
    set {library = .indexLibrary(newValue)}
  }

  /// The library is a local library.
  var localLibrary: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.LocalLibrary {
    get {
      if case .localLibrary(let v)? = library {return v}
      return Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.LocalLibrary()
    }
    set {library = .localLibrary(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Library: Equatable, Sendable {
    /// The library is installed from the Library Index.
    case indexLibrary(Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.IndexLibrary)
    /// The library is a local library.
    case localLibrary(Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.LocalLibrary)

  }

  nonisolated struct IndexLibrary: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Name of the library.
    var name: String = String()

    /// Version of the library if taken from the Library Index.
    var version: String = String()

    /// If true, this library is marked as a dependency.
    var isDependency: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  nonisolated struct LocalLibrary: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Absolute path to the library.
    var path: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "cc.arduino.cli.commands.v1"

nonisolated extension Cc_Arduino_Cli_Commands_V1_Instance: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Instance"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.id) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt32Field(value: self.id, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Instance, rhs: Cc_Arduino_Cli_Commands_V1_Instance) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DownloadProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DownloadProgress"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}start\0\u{1}update\0\u{1}end\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Cc_Arduino_Cli_Commands_V1_DownloadProgressStart?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .start(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .start(v)
        }
      }()
      case 2: try {
        var v: Cc_Arduino_Cli_Commands_V1_DownloadProgressUpdate?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .update(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .update(v)
        }
      }()
      case 3: try {
        var v: Cc_Arduino_Cli_Commands_V1_DownloadProgressEnd?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .end(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .end(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .start?: try {
      guard case .start(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .update?: try {
      guard case .update(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .end?: try {
      guard case .end(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DownloadProgress, rhs: Cc_Arduino_Cli_Commands_V1_DownloadProgress) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DownloadProgressStart: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DownloadProgressStart"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}url\0\u{1}label\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.label) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 1)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DownloadProgressStart, rhs: Cc_Arduino_Cli_Commands_V1_DownloadProgressStart) -> Bool {
    if lhs.url != rhs.url {return false}
    if lhs.label != rhs.label {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DownloadProgressUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DownloadProgressUpdate"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}downloaded\0\u{3}total_size\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.downloaded) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.totalSize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.downloaded != 0 {
      try visitor.visitSingularInt64Field(value: self.downloaded, fieldNumber: 1)
    }
    if self.totalSize != 0 {
      try visitor.visitSingularInt64Field(value: self.totalSize, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DownloadProgressUpdate, rhs: Cc_Arduino_Cli_Commands_V1_DownloadProgressUpdate) -> Bool {
    if lhs.downloaded != rhs.downloaded {return false}
    if lhs.totalSize != rhs.totalSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DownloadProgressEnd: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DownloadProgressEnd"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DownloadProgressEnd, rhs: Cc_Arduino_Cli_Commands_V1_DownloadProgressEnd) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_TaskProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TaskProgress"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}message\0\u{1}completed\0\u{1}percent\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.completed) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.percent) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if self.completed != false {
      try visitor.visitSingularBoolField(value: self.completed, fieldNumber: 3)
    }
    if self.percent.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.percent, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_TaskProgress, rhs: Cc_Arduino_Cli_Commands_V1_TaskProgress) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.message != rhs.message {return false}
    if lhs.completed != rhs.completed {return false}
    if lhs.percent != rhs.percent {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Programmer: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Programmer"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}platform\0\u{1}id\0\u{1}name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 2)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Programmer, rhs: Cc_Arduino_Cli_Commands_V1_Programmer) -> Bool {
    if lhs.platform != rhs.platform {return false}
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_MissingProgrammerError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MissingProgrammerError"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_MissingProgrammerError, rhs: Cc_Arduino_Cli_Commands_V1_MissingProgrammerError) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Platform: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Platform"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}metadata\0\u{1}release\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._release) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._release {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Platform, rhs: Cc_Arduino_Cli_Commands_V1_Platform) -> Bool {
    if lhs._metadata != rhs._metadata {return false}
    if lhs._release != rhs._release {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformSummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformSummary"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}metadata\0\u{1}releases\0\u{3}installed_version\0\u{3}latest_version\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._metadata) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Cc_Arduino_Cli_Commands_V1_PlatformRelease>.self, value: &self.releases) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.installedVersion) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.latestVersion) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._metadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.releases.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Cc_Arduino_Cli_Commands_V1_PlatformRelease>.self, value: self.releases, fieldNumber: 2)
    }
    if !self.installedVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.installedVersion, fieldNumber: 3)
    }
    if !self.latestVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.latestVersion, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformSummary, rhs: Cc_Arduino_Cli_Commands_V1_PlatformSummary) -> Bool {
    if lhs._metadata != rhs._metadata {return false}
    if lhs.releases != rhs.releases {return false}
    if lhs.installedVersion != rhs.installedVersion {return false}
    if lhs.latestVersion != rhs.latestVersion {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformMetadata"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}maintainer\0\u{1}website\0\u{1}email\0\u{3}manually_installed\0\u{1}deprecated\0\u{1}indexed\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.maintainer) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.website) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.email) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.manuallyInstalled) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.deprecated) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.indexed) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.maintainer.isEmpty {
      try visitor.visitSingularStringField(value: self.maintainer, fieldNumber: 2)
    }
    if !self.website.isEmpty {
      try visitor.visitSingularStringField(value: self.website, fieldNumber: 3)
    }
    if !self.email.isEmpty {
      try visitor.visitSingularStringField(value: self.email, fieldNumber: 4)
    }
    if self.manuallyInstalled != false {
      try visitor.visitSingularBoolField(value: self.manuallyInstalled, fieldNumber: 5)
    }
    if self.deprecated != false {
      try visitor.visitSingularBoolField(value: self.deprecated, fieldNumber: 6)
    }
    if self.indexed != false {
      try visitor.visitSingularBoolField(value: self.indexed, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformMetadata, rhs: Cc_Arduino_Cli_Commands_V1_PlatformMetadata) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.maintainer != rhs.maintainer {return false}
    if lhs.website != rhs.website {return false}
    if lhs.email != rhs.email {return false}
    if lhs.manuallyInstalled != rhs.manuallyInstalled {return false}
    if lhs.deprecated != rhs.deprecated {return false}
    if lhs.indexed != rhs.indexed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformRelease: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformRelease"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}version\0\u{1}types\0\u{1}installed\0\u{1}boards\0\u{1}help\0\u{3}missing_metadata\0\u{1}deprecated\0\u{1}compatible\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.types) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.installed) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.boards) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._help) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.missingMetadata) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.deprecated) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self.compatible) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 2)
    }
    if !self.types.isEmpty {
      try visitor.visitRepeatedStringField(value: self.types, fieldNumber: 3)
    }
    if self.installed != false {
      try visitor.visitSingularBoolField(value: self.installed, fieldNumber: 4)
    }
    if !self.boards.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.boards, fieldNumber: 5)
    }
    try { if let v = self._help {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if self.missingMetadata != false {
      try visitor.visitSingularBoolField(value: self.missingMetadata, fieldNumber: 7)
    }
    if self.deprecated != false {
      try visitor.visitSingularBoolField(value: self.deprecated, fieldNumber: 8)
    }
    if self.compatible != false {
      try visitor.visitSingularBoolField(value: self.compatible, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformRelease, rhs: Cc_Arduino_Cli_Commands_V1_PlatformRelease) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.version != rhs.version {return false}
    if lhs.types != rhs.types {return false}
    if lhs.installed != rhs.installed {return false}
    if lhs.boards != rhs.boards {return false}
    if lhs._help != rhs._help {return false}
    if lhs.missingMetadata != rhs.missingMetadata {return false}
    if lhs.deprecated != rhs.deprecated {return false}
    if lhs.compatible != rhs.compatible {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InstalledPlatformReference"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}version\0\u{3}install_dir\0\u{3}package_url\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.installDir) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.packageURL) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 2)
    }
    if !self.installDir.isEmpty {
      try visitor.visitSingularStringField(value: self.installDir, fieldNumber: 3)
    }
    if !self.packageURL.isEmpty {
      try visitor.visitSingularStringField(value: self.packageURL, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference, rhs: Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.version != rhs.version {return false}
    if lhs.installDir != rhs.installDir {return false}
    if lhs.packageURL != rhs.packageURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Board: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Board"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}fqbn\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Board, rhs: Cc_Arduino_Cli_Commands_V1_Board) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_HelpResources: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".HelpResources"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}online\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.online) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.online.isEmpty {
      try visitor.visitSingularStringField(value: self.online, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_HelpResources, rhs: Cc_Arduino_Cli_Commands_V1_HelpResources) -> Bool {
    if lhs.online != rhs.online {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Sketch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Sketch"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}main_file\0\u{3}location_path\0\u{3}other_sketch_files\0\u{3}additional_files\0\u{3}root_folder_files\0\u{3}default_fqbn\0\u{3}default_port\0\u{3}default_protocol\0\u{1}profiles\0\u{3}default_profile\0\u{3}default_programmer\0\u{3}default_port_config\0")

  fileprivate class _StorageClass {
    var _mainFile: String = String()
    var _locationPath: String = String()
    var _otherSketchFiles: [String] = []
    var _additionalFiles: [String] = []
    var _rootFolderFiles: [String] = []
    var _defaultFqbn: String = String()
    var _defaultPort: String = String()
    var _defaultProtocol: String = String()
    var _profiles: [Cc_Arduino_Cli_Commands_V1_SketchProfile] = []
    var _defaultProfile: Cc_Arduino_Cli_Commands_V1_SketchProfile? = nil
    var _defaultProgrammer: String = String()
    var _defaultPortConfig: Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _mainFile = source._mainFile
      _locationPath = source._locationPath
      _otherSketchFiles = source._otherSketchFiles
      _additionalFiles = source._additionalFiles
      _rootFolderFiles = source._rootFolderFiles
      _defaultFqbn = source._defaultFqbn
      _defaultPort = source._defaultPort
      _defaultProtocol = source._defaultProtocol
      _profiles = source._profiles
      _defaultProfile = source._defaultProfile
      _defaultProgrammer = source._defaultProgrammer
      _defaultPortConfig = source._defaultPortConfig
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._mainFile) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._locationPath) }()
        case 3: try { try decoder.decodeRepeatedStringField(value: &_storage._otherSketchFiles) }()
        case 4: try { try decoder.decodeRepeatedStringField(value: &_storage._additionalFiles) }()
        case 5: try { try decoder.decodeRepeatedStringField(value: &_storage._rootFolderFiles) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._defaultFqbn) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._defaultPort) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._defaultProtocol) }()
        case 9: try { try decoder.decodeRepeatedMessageField(value: &_storage._profiles) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._defaultProfile) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._defaultProgrammer) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._defaultPortConfig) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._mainFile.isEmpty {
        try visitor.visitSingularStringField(value: _storage._mainFile, fieldNumber: 1)
      }
      if !_storage._locationPath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._locationPath, fieldNumber: 2)
      }
      if !_storage._otherSketchFiles.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._otherSketchFiles, fieldNumber: 3)
      }
      if !_storage._additionalFiles.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._additionalFiles, fieldNumber: 4)
      }
      if !_storage._rootFolderFiles.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._rootFolderFiles, fieldNumber: 5)
      }
      if !_storage._defaultFqbn.isEmpty {
        try visitor.visitSingularStringField(value: _storage._defaultFqbn, fieldNumber: 6)
      }
      if !_storage._defaultPort.isEmpty {
        try visitor.visitSingularStringField(value: _storage._defaultPort, fieldNumber: 7)
      }
      if !_storage._defaultProtocol.isEmpty {
        try visitor.visitSingularStringField(value: _storage._defaultProtocol, fieldNumber: 8)
      }
      if !_storage._profiles.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._profiles, fieldNumber: 9)
      }
      try { if let v = _storage._defaultProfile {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      if !_storage._defaultProgrammer.isEmpty {
        try visitor.visitSingularStringField(value: _storage._defaultProgrammer, fieldNumber: 11)
      }
      try { if let v = _storage._defaultPortConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Sketch, rhs: Cc_Arduino_Cli_Commands_V1_Sketch) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._mainFile != rhs_storage._mainFile {return false}
        if _storage._locationPath != rhs_storage._locationPath {return false}
        if _storage._otherSketchFiles != rhs_storage._otherSketchFiles {return false}
        if _storage._additionalFiles != rhs_storage._additionalFiles {return false}
        if _storage._rootFolderFiles != rhs_storage._rootFolderFiles {return false}
        if _storage._defaultFqbn != rhs_storage._defaultFqbn {return false}
        if _storage._defaultPort != rhs_storage._defaultPort {return false}
        if _storage._defaultProtocol != rhs_storage._defaultProtocol {return false}
        if _storage._profiles != rhs_storage._profiles {return false}
        if _storage._defaultProfile != rhs_storage._defaultProfile {return false}
        if _storage._defaultProgrammer != rhs_storage._defaultProgrammer {return false}
        if _storage._defaultPortConfig != rhs_storage._defaultPortConfig {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MonitorPortConfiguration"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}settings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.settings) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.settings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.settings, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration, rhs: Cc_Arduino_Cli_Commands_V1_MonitorPortConfiguration) -> Bool {
    if lhs.settings != rhs.settings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_MonitorPortSetting: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MonitorPortSetting"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}setting_id\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.settingID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.settingID.isEmpty {
      try visitor.visitSingularStringField(value: self.settingID, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_MonitorPortSetting, rhs: Cc_Arduino_Cli_Commands_V1_MonitorPortSetting) -> Bool {
    if lhs.settingID != rhs.settingID {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SketchProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SketchProfile"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}fqbn\0\u{1}programmer\0\u{1}port\0\u{3}port_config\0\u{1}protocol\0\u{1}platforms\0\u{1}libraries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.programmer) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.port) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._portConfig) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.`protocol`) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.platforms) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.libraries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 2)
    }
    if !self.programmer.isEmpty {
      try visitor.visitSingularStringField(value: self.programmer, fieldNumber: 3)
    }
    if !self.port.isEmpty {
      try visitor.visitSingularStringField(value: self.port, fieldNumber: 4)
    }
    try { if let v = self._portConfig {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.`protocol`.isEmpty {
      try visitor.visitSingularStringField(value: self.`protocol`, fieldNumber: 6)
    }
    if !self.platforms.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.platforms, fieldNumber: 7)
    }
    if !self.libraries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.libraries, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SketchProfile, rhs: Cc_Arduino_Cli_Commands_V1_SketchProfile) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs.programmer != rhs.programmer {return false}
    if lhs.port != rhs.port {return false}
    if lhs._portConfig != rhs._portConfig {return false}
    if lhs.`protocol` != rhs.`protocol` {return false}
    if lhs.platforms != rhs.platforms {return false}
    if lhs.libraries != rhs.libraries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ProfilePlatformReference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProfilePlatformReference"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}version\0\u{3}index_url\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._version) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._indexURL) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    try { if let v = self._version {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._indexURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ProfilePlatformReference, rhs: Cc_Arduino_Cli_Commands_V1_ProfilePlatformReference) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs._version != rhs._version {return false}
    if lhs._indexURL != rhs._indexURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProfileLibraryReference"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}index_library\0\u{3}local_library\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.IndexLibrary?
        var hadOneofValue = false
        if let current = self.library {
          hadOneofValue = true
          if case .indexLibrary(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.library = .indexLibrary(v)
        }
      }()
      case 2: try {
        var v: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.LocalLibrary?
        var hadOneofValue = false
        if let current = self.library {
          hadOneofValue = true
          if case .localLibrary(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.library = .localLibrary(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.library {
    case .indexLibrary?: try {
      guard case .indexLibrary(let v)? = self.library else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .localLibrary?: try {
      guard case .localLibrary(let v)? = self.library else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference, rhs: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference) -> Bool {
    if lhs.library != rhs.library {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.IndexLibrary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.protoMessageName + ".IndexLibrary"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}version\0\u{3}is_dependency\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isDependency) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 2)
    }
    if self.isDependency != false {
      try visitor.visitSingularBoolField(value: self.isDependency, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.IndexLibrary, rhs: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.IndexLibrary) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.version != rhs.version {return false}
    if lhs.isDependency != rhs.isDependency {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.LocalLibrary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.protoMessageName + ".LocalLibrary"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.LocalLibrary, rhs: Cc_Arduino_Cli_Commands_V1_ProfileLibraryReference.LocalLibrary) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
