// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cc/arduino/cli/commands/v1/debug.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This file is part of arduino-cli.
//
// Copyright 2024 ARDUINO SA (https://www.arduino.cc/)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The top-level message sent by the client for the `Debug` method.
/// Multiple `DebugRequest` messages can be sent but the first message
/// must contain a `GetDebugConfigRequest` message to initialize the debug
/// session. All subsequent messages must contain bytes to be sent to the debug
/// session and must not contain a `GetDebugConfigRequest` message.
nonisolated struct Cc_Arduino_Cli_Commands_V1_DebugRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Provides information to the debug that specifies which is the target.
  /// The first `DebugRequest` message must contain a `GetDebugConfigRequest`
  /// message.
  var debugRequest: Cc_Arduino_Cli_Commands_V1_GetDebugConfigRequest {
    get {_debugRequest ?? Cc_Arduino_Cli_Commands_V1_GetDebugConfigRequest()}
    set {_debugRequest = newValue}
  }
  /// Returns true if `debugRequest` has been explicitly set.
  var hasDebugRequest: Bool {self._debugRequest != nil}
  /// Clears the value of `debugRequest`. Subsequent reads from it will return its default value.
  mutating func clearDebugRequest() {self._debugRequest = nil}

  /// The data to be sent to the target being monitored.
  var data: Data = Data()

  /// Set this to true to send and Interrupt signal to the debugger process.
  var sendInterrupt: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _debugRequest: Cc_Arduino_Cli_Commands_V1_GetDebugConfigRequest? = nil
}

/// The streaming response may contain chunks of data from the debugger or an
/// error.
nonisolated struct Cc_Arduino_Cli_Commands_V1_DebugResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_DebugResponse.OneOf_Message? = nil

  /// Incoming data from the debugger tool.
  var data: Data {
    get {
      if case .data(let v)? = message {return v}
      return Data()
    }
    set {message = .data(newValue)}
  }

  /// Debugging result.
  var result: Cc_Arduino_Cli_Commands_V1_DebugResponse.Result {
    get {
      if case .result(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_DebugResponse.Result()
    }
    set {message = .result(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// Incoming data from the debugger tool.
    case data(Data)
    /// Debugging result.
    case result(Cc_Arduino_Cli_Commands_V1_DebugResponse.Result)

  }

  nonisolated struct Result: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Incoming error output from the debugger tool.
    var error: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_IsDebugSupportedRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Fully qualified board name of the board in use (e.g.,
  /// `arduino:samd:mkr1000`).
  var fqbn: String = String()

  /// Port of the debugger (optional).
  var port: Cc_Arduino_Cli_Commands_V1_Port {
    get {_port ?? Cc_Arduino_Cli_Commands_V1_Port()}
    set {_port = newValue}
  }
  /// Returns true if `port` has been explicitly set.
  var hasPort: Bool {self._port != nil}
  /// Clears the value of `port`. Subsequent reads from it will return its default value.
  mutating func clearPort() {self._port = nil}

  /// Which GDB command interpreter to use.
  var interpreter: String = String()

  /// The programmer to use for debugging.
  var programmer: String = String()

  /// List of custom debug properties.
  var debugProperties: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
  fileprivate var _port: Cc_Arduino_Cli_Commands_V1_Port? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_IsDebugSupportedResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// True if debugging is supported.
  var debuggingSupported: Bool = false

  /// This is the same FQBN given in the IsDebugSupportedRequest but cleaned
  /// up of the board options that do not affect the debugger configuration.
  /// It may be used by clients/IDE to group slightly different boards option
  /// selections under the same debug configuration.
  var debugFqbn: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_GetDebugConfigRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Fully qualified board name of the board in use
  /// (e.g., `arduino:samd:mkr1000`). If this is omitted, the FQBN attached to
  /// the sketch will be used.
  var fqbn: String = String()

  /// Path to the sketch that is running on the board. The compiled executable
  /// is expected to be located under this path.
  var sketchPath: String = String()

  /// Port of the debugger (optional).
  var port: Cc_Arduino_Cli_Commands_V1_Port {
    get {_port ?? Cc_Arduino_Cli_Commands_V1_Port()}
    set {_port = newValue}
  }
  /// Returns true if `port` has been explicitly set.
  var hasPort: Bool {self._port != nil}
  /// Clears the value of `port`. Subsequent reads from it will return its default value.
  mutating func clearPort() {self._port = nil}

  /// Which GDB command interpreter to use.
  var interpreter: String = String()

  /// Directory containing the compiled executable. If `import_dir` is not
  /// specified, the executable is assumed to be in
  /// `{sketch_path}/build/{fqbn}/`.
  var importDir: String = String()

  /// The programmer to use for debugging.
  var programmer: String = String()

  /// List of custom debug properties.
  var debugProperties: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
  fileprivate var _port: Cc_Arduino_Cli_Commands_V1_Port? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_GetDebugConfigResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The executable binary to debug.
  var executable: String = String()

  /// The toolchain type used for the build (for example "gcc").
  var toolchain: String = String()

  /// The toolchain directory.
  var toolchainPath: String = String()

  /// The toolchain architecture prefix (for example "arm-none-eabi").
  var toolchainPrefix: String = String()

  /// The GDB server type used to connect to the programmer/board (for example
  /// "openocd").
  var server: String = String()

  /// The GDB server directory.
  var serverPath: String = String()

  /// Extra configuration parameters wrt toolchain.
  var toolchainConfiguration: SwiftProtobuf.Google_Protobuf_Any {
    get {_toolchainConfiguration ?? SwiftProtobuf.Google_Protobuf_Any()}
    set {_toolchainConfiguration = newValue}
  }
  /// Returns true if `toolchainConfiguration` has been explicitly set.
  var hasToolchainConfiguration: Bool {self._toolchainConfiguration != nil}
  /// Clears the value of `toolchainConfiguration`. Subsequent reads from it will return its default value.
  mutating func clearToolchainConfiguration() {self._toolchainConfiguration = nil}

  /// Extra configuration parameters wrt GDB server.
  var serverConfiguration: SwiftProtobuf.Google_Protobuf_Any {
    get {_serverConfiguration ?? SwiftProtobuf.Google_Protobuf_Any()}
    set {_serverConfiguration = newValue}
  }
  /// Returns true if `serverConfiguration` has been explicitly set.
  var hasServerConfiguration: Bool {self._serverConfiguration != nil}
  /// Clears the value of `serverConfiguration`. Subsequent reads from it will return its default value.
  mutating func clearServerConfiguration() {self._serverConfiguration = nil}

  /// Custom debugger configurations (not handled directly by Arduino CLI but
  /// provided for 3rd party plugins/debuggers). The map keys identifies which
  /// 3rd party plugin/debugger is referred, the map string values contains a
  /// JSON configuration for it.
  var customConfigs: Dictionary<String,String> = [:]

  /// the SVD file to use.
  var svdFile: String = String()

  /// The programmer specified in the request.
  var programmer: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _toolchainConfiguration: SwiftProtobuf.Google_Protobuf_Any? = nil
  fileprivate var _serverConfiguration: SwiftProtobuf.Google_Protobuf_Any? = nil
}

/// Configurations specific for the 'gcc' toolchain.
nonisolated struct Cc_Arduino_Cli_Commands_V1_DebugGCCToolchainConfiguration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Configuration specific for the 'openocd` server.
nonisolated struct Cc_Arduino_Cli_Commands_V1_DebugOpenOCDServerConfiguration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Path to openocd.
  var path: String = String()

  /// Path to openocd scripts.
  var scriptsDir: String = String()

  /// List of scripts to execute by openocd.
  var scripts: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "cc.arduino.cli.commands.v1"

nonisolated extension Cc_Arduino_Cli_Commands_V1_DebugRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DebugRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}debug_request\0\u{1}data\0\u{3}send_interrupt\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._debugRequest) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.sendInterrupt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._debugRequest {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 2)
    }
    if self.sendInterrupt != false {
      try visitor.visitSingularBoolField(value: self.sendInterrupt, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DebugRequest, rhs: Cc_Arduino_Cli_Commands_V1_DebugRequest) -> Bool {
    if lhs._debugRequest != rhs._debugRequest {return false}
    if lhs.data != rhs.data {return false}
    if lhs.sendInterrupt != rhs.sendInterrupt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DebugResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DebugResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{1}result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .data(v)
        }
      }()
      case 2: try {
        var v: Cc_Arduino_Cli_Commands_V1_DebugResponse.Result?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .result(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .result(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .data?: try {
      guard case .data(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    }()
    case .result?: try {
      guard case .result(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DebugResponse, rhs: Cc_Arduino_Cli_Commands_V1_DebugResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DebugResponse.Result: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_DebugResponse.protoMessageName + ".Result"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.error) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.error.isEmpty {
      try visitor.visitSingularStringField(value: self.error, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DebugResponse.Result, rhs: Cc_Arduino_Cli_Commands_V1_DebugResponse.Result) -> Bool {
    if lhs.error != rhs.error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_IsDebugSupportedRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".IsDebugSupportedRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0\u{1}port\0\u{1}interpreter\0\u{1}programmer\0\u{3}debug_properties\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._port) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.interpreter) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.programmer) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.debugProperties) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 2)
    }
    try { if let v = self._port {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if !self.interpreter.isEmpty {
      try visitor.visitSingularStringField(value: self.interpreter, fieldNumber: 4)
    }
    if !self.programmer.isEmpty {
      try visitor.visitSingularStringField(value: self.programmer, fieldNumber: 5)
    }
    if !self.debugProperties.isEmpty {
      try visitor.visitRepeatedStringField(value: self.debugProperties, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_IsDebugSupportedRequest, rhs: Cc_Arduino_Cli_Commands_V1_IsDebugSupportedRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs._port != rhs._port {return false}
    if lhs.interpreter != rhs.interpreter {return false}
    if lhs.programmer != rhs.programmer {return false}
    if lhs.debugProperties != rhs.debugProperties {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_IsDebugSupportedResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".IsDebugSupportedResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}debugging_supported\0\u{3}debug_fqbn\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.debuggingSupported) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.debugFqbn) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.debuggingSupported != false {
      try visitor.visitSingularBoolField(value: self.debuggingSupported, fieldNumber: 1)
    }
    if !self.debugFqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.debugFqbn, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_IsDebugSupportedResponse, rhs: Cc_Arduino_Cli_Commands_V1_IsDebugSupportedResponse) -> Bool {
    if lhs.debuggingSupported != rhs.debuggingSupported {return false}
    if lhs.debugFqbn != rhs.debugFqbn {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_GetDebugConfigRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetDebugConfigRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0\u{3}sketch_path\0\u{1}port\0\u{1}interpreter\0\u{4}\u{3}import_dir\0\u{1}programmer\0\u{3}debug_properties\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sketchPath) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._port) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.interpreter) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.importDir) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.programmer) }()
      case 10: try { try decoder.decodeRepeatedStringField(value: &self.debugProperties) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 2)
    }
    if !self.sketchPath.isEmpty {
      try visitor.visitSingularStringField(value: self.sketchPath, fieldNumber: 3)
    }
    try { if let v = self._port {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.interpreter.isEmpty {
      try visitor.visitSingularStringField(value: self.interpreter, fieldNumber: 5)
    }
    if !self.importDir.isEmpty {
      try visitor.visitSingularStringField(value: self.importDir, fieldNumber: 8)
    }
    if !self.programmer.isEmpty {
      try visitor.visitSingularStringField(value: self.programmer, fieldNumber: 9)
    }
    if !self.debugProperties.isEmpty {
      try visitor.visitRepeatedStringField(value: self.debugProperties, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_GetDebugConfigRequest, rhs: Cc_Arduino_Cli_Commands_V1_GetDebugConfigRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs.sketchPath != rhs.sketchPath {return false}
    if lhs._port != rhs._port {return false}
    if lhs.interpreter != rhs.interpreter {return false}
    if lhs.importDir != rhs.importDir {return false}
    if lhs.programmer != rhs.programmer {return false}
    if lhs.debugProperties != rhs.debugProperties {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_GetDebugConfigResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetDebugConfigResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}executable\0\u{1}toolchain\0\u{3}toolchain_path\0\u{3}toolchain_prefix\0\u{1}server\0\u{3}server_path\0\u{3}toolchain_configuration\0\u{3}server_configuration\0\u{3}custom_configs\0\u{3}svd_file\0\u{1}programmer\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.executable) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.toolchain) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.toolchainPath) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.toolchainPrefix) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.server) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.serverPath) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._toolchainConfiguration) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._serverConfiguration) }()
      case 9: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.customConfigs) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.svdFile) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.programmer) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.executable.isEmpty {
      try visitor.visitSingularStringField(value: self.executable, fieldNumber: 1)
    }
    if !self.toolchain.isEmpty {
      try visitor.visitSingularStringField(value: self.toolchain, fieldNumber: 2)
    }
    if !self.toolchainPath.isEmpty {
      try visitor.visitSingularStringField(value: self.toolchainPath, fieldNumber: 3)
    }
    if !self.toolchainPrefix.isEmpty {
      try visitor.visitSingularStringField(value: self.toolchainPrefix, fieldNumber: 4)
    }
    if !self.server.isEmpty {
      try visitor.visitSingularStringField(value: self.server, fieldNumber: 5)
    }
    if !self.serverPath.isEmpty {
      try visitor.visitSingularStringField(value: self.serverPath, fieldNumber: 6)
    }
    try { if let v = self._toolchainConfiguration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._serverConfiguration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if !self.customConfigs.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.customConfigs, fieldNumber: 9)
    }
    if !self.svdFile.isEmpty {
      try visitor.visitSingularStringField(value: self.svdFile, fieldNumber: 10)
    }
    if !self.programmer.isEmpty {
      try visitor.visitSingularStringField(value: self.programmer, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_GetDebugConfigResponse, rhs: Cc_Arduino_Cli_Commands_V1_GetDebugConfigResponse) -> Bool {
    if lhs.executable != rhs.executable {return false}
    if lhs.toolchain != rhs.toolchain {return false}
    if lhs.toolchainPath != rhs.toolchainPath {return false}
    if lhs.toolchainPrefix != rhs.toolchainPrefix {return false}
    if lhs.server != rhs.server {return false}
    if lhs.serverPath != rhs.serverPath {return false}
    if lhs._toolchainConfiguration != rhs._toolchainConfiguration {return false}
    if lhs._serverConfiguration != rhs._serverConfiguration {return false}
    if lhs.customConfigs != rhs.customConfigs {return false}
    if lhs.svdFile != rhs.svdFile {return false}
    if lhs.programmer != rhs.programmer {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DebugGCCToolchainConfiguration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DebugGCCToolchainConfiguration"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DebugGCCToolchainConfiguration, rhs: Cc_Arduino_Cli_Commands_V1_DebugGCCToolchainConfiguration) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DebugOpenOCDServerConfiguration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DebugOpenOCDServerConfiguration"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0\u{3}scripts_dir\0\u{1}scripts\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.scriptsDir) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.scripts) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if !self.scriptsDir.isEmpty {
      try visitor.visitSingularStringField(value: self.scriptsDir, fieldNumber: 2)
    }
    if !self.scripts.isEmpty {
      try visitor.visitRepeatedStringField(value: self.scripts, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DebugOpenOCDServerConfiguration, rhs: Cc_Arduino_Cli_Commands_V1_DebugOpenOCDServerConfiguration) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.scriptsDir != rhs.scriptsDir {return false}
    if lhs.scripts != rhs.scripts {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
