// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cc/arduino/cli/commands/v1/settings.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This file is part of arduino-cli.
//
// Copyright 2024 ARDUINO SA (https://www.arduino.cc/)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Configuration to apply to the given instance.
/// Any missing field will be kept at the default value.
nonisolated struct Cc_Arduino_Cli_Commands_V1_Configuration: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The directories configuration.
  var directories: Cc_Arduino_Cli_Commands_V1_Configuration.Directories {
    get {_storage._directories ?? Cc_Arduino_Cli_Commands_V1_Configuration.Directories()}
    set {_uniqueStorage()._directories = newValue}
  }
  /// Returns true if `directories` has been explicitly set.
  var hasDirectories: Bool {_storage._directories != nil}
  /// Clears the value of `directories`. Subsequent reads from it will return its default value.
  mutating func clearDirectories() {_uniqueStorage()._directories = nil}

  /// The network configuration.
  var network: Cc_Arduino_Cli_Commands_V1_Configuration.Network {
    get {_storage._network ?? Cc_Arduino_Cli_Commands_V1_Configuration.Network()}
    set {_uniqueStorage()._network = newValue}
  }
  /// Returns true if `network` has been explicitly set.
  var hasNetwork: Bool {_storage._network != nil}
  /// Clears the value of `network`. Subsequent reads from it will return its default value.
  mutating func clearNetwork() {_uniqueStorage()._network = nil}

  /// The sketch configuration.
  var sketch: Cc_Arduino_Cli_Commands_V1_Configuration.Sketch {
    get {_storage._sketch ?? Cc_Arduino_Cli_Commands_V1_Configuration.Sketch()}
    set {_uniqueStorage()._sketch = newValue}
  }
  /// Returns true if `sketch` has been explicitly set.
  var hasSketch: Bool {_storage._sketch != nil}
  /// Clears the value of `sketch`. Subsequent reads from it will return its default value.
  mutating func clearSketch() {_uniqueStorage()._sketch = nil}

  /// The build cache configuration.
  var buildCache: Cc_Arduino_Cli_Commands_V1_Configuration.BuildCache {
    get {_storage._buildCache ?? Cc_Arduino_Cli_Commands_V1_Configuration.BuildCache()}
    set {_uniqueStorage()._buildCache = newValue}
  }
  /// Returns true if `buildCache` has been explicitly set.
  var hasBuildCache: Bool {_storage._buildCache != nil}
  /// Clears the value of `buildCache`. Subsequent reads from it will return its default value.
  mutating func clearBuildCache() {_uniqueStorage()._buildCache = nil}

  /// The board manager configuration.
  var boardManager: Cc_Arduino_Cli_Commands_V1_Configuration.BoardManager {
    get {_storage._boardManager ?? Cc_Arduino_Cli_Commands_V1_Configuration.BoardManager()}
    set {_uniqueStorage()._boardManager = newValue}
  }
  /// Returns true if `boardManager` has been explicitly set.
  var hasBoardManager: Bool {_storage._boardManager != nil}
  /// Clears the value of `boardManager`. Subsequent reads from it will return its default value.
  mutating func clearBoardManager() {_uniqueStorage()._boardManager = nil}

  /// The daemon configuration.
  var daemon: Cc_Arduino_Cli_Commands_V1_Configuration.Daemon {
    get {_storage._daemon ?? Cc_Arduino_Cli_Commands_V1_Configuration.Daemon()}
    set {_uniqueStorage()._daemon = newValue}
  }
  /// Returns true if `daemon` has been explicitly set.
  var hasDaemon: Bool {_storage._daemon != nil}
  /// Clears the value of `daemon`. Subsequent reads from it will return its default value.
  mutating func clearDaemon() {_uniqueStorage()._daemon = nil}

  /// The console output configuration.
  var output: Cc_Arduino_Cli_Commands_V1_Configuration.Output {
    get {_storage._output ?? Cc_Arduino_Cli_Commands_V1_Configuration.Output()}
    set {_uniqueStorage()._output = newValue}
  }
  /// Returns true if `output` has been explicitly set.
  var hasOutput: Bool {_storage._output != nil}
  /// Clears the value of `output`. Subsequent reads from it will return its default value.
  mutating func clearOutput() {_uniqueStorage()._output = nil}

  /// The logging configuration.
  var logging: Cc_Arduino_Cli_Commands_V1_Configuration.Logging {
    get {_storage._logging ?? Cc_Arduino_Cli_Commands_V1_Configuration.Logging()}
    set {_uniqueStorage()._logging = newValue}
  }
  /// Returns true if `logging` has been explicitly set.
  var hasLogging: Bool {_storage._logging != nil}
  /// Clears the value of `logging`. Subsequent reads from it will return its default value.
  mutating func clearLogging() {_uniqueStorage()._logging = nil}

  /// The library configuration.
  var library: Cc_Arduino_Cli_Commands_V1_Configuration.Library {
    get {_storage._library ?? Cc_Arduino_Cli_Commands_V1_Configuration.Library()}
    set {_uniqueStorage()._library = newValue}
  }
  /// Returns true if `library` has been explicitly set.
  var hasLibrary: Bool {_storage._library != nil}
  /// Clears the value of `library`. Subsequent reads from it will return its default value.
  mutating func clearLibrary() {_uniqueStorage()._library = nil}

  /// The updater configuration.
  var updater: Cc_Arduino_Cli_Commands_V1_Configuration.Updater {
    get {_storage._updater ?? Cc_Arduino_Cli_Commands_V1_Configuration.Updater()}
    set {_uniqueStorage()._updater = newValue}
  }
  /// Returns true if `updater` has been explicitly set.
  var hasUpdater: Bool {_storage._updater != nil}
  /// Clears the value of `updater`. Subsequent reads from it will return its default value.
  mutating func clearUpdater() {_uniqueStorage()._updater = nil}

  /// The language locale to use.
  var locale: String {
    get {_storage._locale ?? String()}
    set {_uniqueStorage()._locale = newValue}
  }
  /// Returns true if `locale` has been explicitly set.
  var hasLocale: Bool {_storage._locale != nil}
  /// Clears the value of `locale`. Subsequent reads from it will return its default value.
  mutating func clearLocale() {_uniqueStorage()._locale = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated struct Directories: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Data directory.
    var data: String = String()

    /// User directory.
    var user: String = String()

    /// Downloads directory.
    var downloads: String = String()

    /// The directory where the built-in resources are installed.
    var builtin: Cc_Arduino_Cli_Commands_V1_Configuration.Directories.Builtin {
      get {_builtin ?? Cc_Arduino_Cli_Commands_V1_Configuration.Directories.Builtin()}
      set {_builtin = newValue}
    }
    /// Returns true if `builtin` has been explicitly set.
    var hasBuiltin: Bool {self._builtin != nil}
    /// Clears the value of `builtin`. Subsequent reads from it will return its default value.
    mutating func clearBuiltin() {self._builtin = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    nonisolated struct Builtin: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      /// The directory where the built-in libraries are installed.
      var libraries: String {
        get {_libraries ?? String()}
        set {_libraries = newValue}
      }
      /// Returns true if `libraries` has been explicitly set.
      var hasLibraries: Bool {self._libraries != nil}
      /// Clears the value of `libraries`. Subsequent reads from it will return its default value.
      mutating func clearLibraries() {self._libraries = nil}

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}

      fileprivate var _libraries: String? = nil
    }

    init() {}

    fileprivate var _builtin: Cc_Arduino_Cli_Commands_V1_Configuration.Directories.Builtin? = nil
  }

  nonisolated struct Network: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Extra user-agent information to be appended in network requests.
    var extraUserAgent: String {
      get {_extraUserAgent ?? String()}
      set {_extraUserAgent = newValue}
    }
    /// Returns true if `extraUserAgent` has been explicitly set.
    var hasExtraUserAgent: Bool {self._extraUserAgent != nil}
    /// Clears the value of `extraUserAgent`. Subsequent reads from it will return its default value.
    mutating func clearExtraUserAgent() {self._extraUserAgent = nil}

    /// The proxy to use for network requests.
    var proxy: String {
      get {_proxy ?? String()}
      set {_proxy = newValue}
    }
    /// Returns true if `proxy` has been explicitly set.
    var hasProxy: Bool {self._proxy != nil}
    /// Clears the value of `proxy`. Subsequent reads from it will return its default value.
    mutating func clearProxy() {self._proxy = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _extraUserAgent: String? = nil
    fileprivate var _proxy: String? = nil
  }

  nonisolated struct Sketch: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Set to true to always export binaries to the sketch directory.
    var alwaysExportBinaries: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  nonisolated struct BuildCache: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The minimum number of compilations before the cache is purged.
    var compilationsBeforePurge: UInt64 = 0

    /// Time to live of the cache in seconds.
    var ttlSecs: UInt64 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  nonisolated struct BoardManager: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Additional URLs to be used for the board manager.
    var additionalUrls: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  nonisolated struct Daemon: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The TCP port of the daemon.
    var port: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  nonisolated struct Output: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Set to true to disable coloring of the output.
    var noColor: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  nonisolated struct Logging: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The logging level.
    var level: String = String()

    /// The logging format.
    var format: String = String()

    /// The logging file.
    var file: String {
      get {_file ?? String()}
      set {_file = newValue}
    }
    /// Returns true if `file` has been explicitly set.
    var hasFile: Bool {self._file != nil}
    /// Clears the value of `file`. Subsequent reads from it will return its default value.
    mutating func clearFile() {self._file = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _file: String? = nil
  }

  nonisolated struct Library: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Set to true to enable library installation from zip archives or git
    /// repositories.
    var enableUnsafeInstall: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  nonisolated struct Updater: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Set to true to enable notifications for updates.
    var enableNotification: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ConfigurationGetRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ConfigurationGetResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The current configuration.
  var configuration: Cc_Arduino_Cli_Commands_V1_Configuration {
    get {_configuration ?? Cc_Arduino_Cli_Commands_V1_Configuration()}
    set {_configuration = newValue}
  }
  /// Returns true if `configuration` has been explicitly set.
  var hasConfiguration: Bool {self._configuration != nil}
  /// Clears the value of `configuration`. Subsequent reads from it will return its default value.
  mutating func clearConfiguration() {self._configuration = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _configuration: Cc_Arduino_Cli_Commands_V1_Configuration? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ConfigurationSaveRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The format of the encoded settings, allowed values are "json" and "yaml".
  var settingsFormat: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ConfigurationSaveResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The encoded settings.
  var encodedSettings: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ConfigurationOpenRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The encoded settings.
  var encodedSettings: String = String()

  /// The format of the encoded settings, allowed values are "json" and "yaml".
  var settingsFormat: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ConfigurationOpenResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Warnings that occurred while opening the configuration (e.g. unknown keys,
  /// or invalid values).
  var warnings: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SettingsGetValueRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The key to get.
  var key: String = String()

  /// The format of the encoded_value (default is "json", allowed values are
  /// "json" and "yaml).
  var valueFormat: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SettingsGetValueResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The value of the key (encoded).
  var encodedValue: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SettingsSetValueRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The key to change.
  var key: String = String()

  /// The new value (encoded), no objects, only scalar or array of scalars are
  /// allowed.
  var encodedValue: String = String()

  /// The format of the encoded_value (default is "json", allowed values are
  /// "json", "yaml" and "cli").
  var valueFormat: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SettingsSetValueResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SettingsEnumerateRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The list of key/value pairs.
  var entries: [Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse.Entry] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated struct Entry: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The key.
    var key: String = String()

    /// The key type.
    var type: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "cc.arduino.cli.commands.v1"

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Configuration"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}directories\0\u{1}network\0\u{1}sketch\0\u{3}build_cache\0\u{3}board_manager\0\u{1}daemon\0\u{1}output\0\u{1}logging\0\u{1}library\0\u{1}updater\0\u{2}Z\u{1}locale\0")

  fileprivate class _StorageClass {
    var _directories: Cc_Arduino_Cli_Commands_V1_Configuration.Directories? = nil
    var _network: Cc_Arduino_Cli_Commands_V1_Configuration.Network? = nil
    var _sketch: Cc_Arduino_Cli_Commands_V1_Configuration.Sketch? = nil
    var _buildCache: Cc_Arduino_Cli_Commands_V1_Configuration.BuildCache? = nil
    var _boardManager: Cc_Arduino_Cli_Commands_V1_Configuration.BoardManager? = nil
    var _daemon: Cc_Arduino_Cli_Commands_V1_Configuration.Daemon? = nil
    var _output: Cc_Arduino_Cli_Commands_V1_Configuration.Output? = nil
    var _logging: Cc_Arduino_Cli_Commands_V1_Configuration.Logging? = nil
    var _library: Cc_Arduino_Cli_Commands_V1_Configuration.Library? = nil
    var _updater: Cc_Arduino_Cli_Commands_V1_Configuration.Updater? = nil
    var _locale: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _directories = source._directories
      _network = source._network
      _sketch = source._sketch
      _buildCache = source._buildCache
      _boardManager = source._boardManager
      _daemon = source._daemon
      _output = source._output
      _logging = source._logging
      _library = source._library
      _updater = source._updater
      _locale = source._locale
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._directories) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._network) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._sketch) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._buildCache) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._boardManager) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._daemon) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._output) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._logging) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._library) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._updater) }()
        case 100: try { try decoder.decodeSingularStringField(value: &_storage._locale) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._directories {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._network {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._sketch {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._buildCache {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._boardManager {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._daemon {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._output {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._logging {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._library {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._updater {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._locale {
        try visitor.visitSingularStringField(value: v, fieldNumber: 100)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration, rhs: Cc_Arduino_Cli_Commands_V1_Configuration) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._directories != rhs_storage._directories {return false}
        if _storage._network != rhs_storage._network {return false}
        if _storage._sketch != rhs_storage._sketch {return false}
        if _storage._buildCache != rhs_storage._buildCache {return false}
        if _storage._boardManager != rhs_storage._boardManager {return false}
        if _storage._daemon != rhs_storage._daemon {return false}
        if _storage._output != rhs_storage._output {return false}
        if _storage._logging != rhs_storage._logging {return false}
        if _storage._library != rhs_storage._library {return false}
        if _storage._updater != rhs_storage._updater {return false}
        if _storage._locale != rhs_storage._locale {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Directories: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".Directories"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{1}user\0\u{1}downloads\0\u{1}builtin\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.data) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.user) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.downloads) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._builtin) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.data.isEmpty {
      try visitor.visitSingularStringField(value: self.data, fieldNumber: 1)
    }
    if !self.user.isEmpty {
      try visitor.visitSingularStringField(value: self.user, fieldNumber: 2)
    }
    if !self.downloads.isEmpty {
      try visitor.visitSingularStringField(value: self.downloads, fieldNumber: 3)
    }
    try { if let v = self._builtin {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Directories, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Directories) -> Bool {
    if lhs.data != rhs.data {return false}
    if lhs.user != rhs.user {return false}
    if lhs.downloads != rhs.downloads {return false}
    if lhs._builtin != rhs._builtin {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Directories.Builtin: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.Directories.protoMessageName + ".Builtin"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}libraries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._libraries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._libraries {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Directories.Builtin, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Directories.Builtin) -> Bool {
    if lhs._libraries != rhs._libraries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Network: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".Network"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}extra_user_agent\0\u{1}proxy\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._extraUserAgent) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._proxy) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._extraUserAgent {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._proxy {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Network, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Network) -> Bool {
    if lhs._extraUserAgent != rhs._extraUserAgent {return false}
    if lhs._proxy != rhs._proxy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Sketch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".Sketch"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}always_export_binaries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.alwaysExportBinaries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.alwaysExportBinaries != false {
      try visitor.visitSingularBoolField(value: self.alwaysExportBinaries, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Sketch, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Sketch) -> Bool {
    if lhs.alwaysExportBinaries != rhs.alwaysExportBinaries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.BuildCache: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".BuildCache"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}compilations_before_purge\0\u{3}ttl_secs\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.compilationsBeforePurge) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.ttlSecs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.compilationsBeforePurge != 0 {
      try visitor.visitSingularUInt64Field(value: self.compilationsBeforePurge, fieldNumber: 1)
    }
    if self.ttlSecs != 0 {
      try visitor.visitSingularUInt64Field(value: self.ttlSecs, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.BuildCache, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.BuildCache) -> Bool {
    if lhs.compilationsBeforePurge != rhs.compilationsBeforePurge {return false}
    if lhs.ttlSecs != rhs.ttlSecs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.BoardManager: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".BoardManager"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}additional_urls\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.additionalUrls) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.additionalUrls.isEmpty {
      try visitor.visitRepeatedStringField(value: self.additionalUrls, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.BoardManager, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.BoardManager) -> Bool {
    if lhs.additionalUrls != rhs.additionalUrls {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Daemon: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".Daemon"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}port\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.port) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.port.isEmpty {
      try visitor.visitSingularStringField(value: self.port, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Daemon, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Daemon) -> Bool {
    if lhs.port != rhs.port {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Output: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".Output"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}no_color\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.noColor) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.noColor != false {
      try visitor.visitSingularBoolField(value: self.noColor, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Output, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Output) -> Bool {
    if lhs.noColor != rhs.noColor {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Logging: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".Logging"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}level\0\u{1}format\0\u{1}file\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.level) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.format) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._file) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.level.isEmpty {
      try visitor.visitSingularStringField(value: self.level, fieldNumber: 1)
    }
    if !self.format.isEmpty {
      try visitor.visitSingularStringField(value: self.format, fieldNumber: 2)
    }
    try { if let v = self._file {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Logging, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Logging) -> Bool {
    if lhs.level != rhs.level {return false}
    if lhs.format != rhs.format {return false}
    if lhs._file != rhs._file {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Library: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".Library"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}enable_unsafe_install\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enableUnsafeInstall) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enableUnsafeInstall != false {
      try visitor.visitSingularBoolField(value: self.enableUnsafeInstall, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Library, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Library) -> Bool {
    if lhs.enableUnsafeInstall != rhs.enableUnsafeInstall {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Configuration.Updater: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_Configuration.protoMessageName + ".Updater"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}enable_notification\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.enableNotification) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.enableNotification != false {
      try visitor.visitSingularBoolField(value: self.enableNotification, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Configuration.Updater, rhs: Cc_Arduino_Cli_Commands_V1_Configuration.Updater) -> Bool {
    if lhs.enableNotification != rhs.enableNotification {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ConfigurationGetRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigurationGetRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ConfigurationGetRequest, rhs: Cc_Arduino_Cli_Commands_V1_ConfigurationGetRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ConfigurationGetResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigurationGetResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}configuration\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._configuration) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._configuration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ConfigurationGetResponse, rhs: Cc_Arduino_Cli_Commands_V1_ConfigurationGetResponse) -> Bool {
    if lhs._configuration != rhs._configuration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ConfigurationSaveRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigurationSaveRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}settings_format\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.settingsFormat) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.settingsFormat.isEmpty {
      try visitor.visitSingularStringField(value: self.settingsFormat, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ConfigurationSaveRequest, rhs: Cc_Arduino_Cli_Commands_V1_ConfigurationSaveRequest) -> Bool {
    if lhs.settingsFormat != rhs.settingsFormat {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ConfigurationSaveResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigurationSaveResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}encoded_settings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.encodedSettings) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.encodedSettings.isEmpty {
      try visitor.visitSingularStringField(value: self.encodedSettings, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ConfigurationSaveResponse, rhs: Cc_Arduino_Cli_Commands_V1_ConfigurationSaveResponse) -> Bool {
    if lhs.encodedSettings != rhs.encodedSettings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ConfigurationOpenRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigurationOpenRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}encoded_settings\0\u{3}settings_format\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.encodedSettings) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.settingsFormat) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.encodedSettings.isEmpty {
      try visitor.visitSingularStringField(value: self.encodedSettings, fieldNumber: 1)
    }
    if !self.settingsFormat.isEmpty {
      try visitor.visitSingularStringField(value: self.settingsFormat, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ConfigurationOpenRequest, rhs: Cc_Arduino_Cli_Commands_V1_ConfigurationOpenRequest) -> Bool {
    if lhs.encodedSettings != rhs.encodedSettings {return false}
    if lhs.settingsFormat != rhs.settingsFormat {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ConfigurationOpenResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigurationOpenResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}warnings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.warnings) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.warnings.isEmpty {
      try visitor.visitRepeatedStringField(value: self.warnings, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ConfigurationOpenResponse, rhs: Cc_Arduino_Cli_Commands_V1_ConfigurationOpenResponse) -> Bool {
    if lhs.warnings != rhs.warnings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SettingsGetValueRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SettingsGetValueRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{3}value_format\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.valueFormat) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if !self.valueFormat.isEmpty {
      try visitor.visitSingularStringField(value: self.valueFormat, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SettingsGetValueRequest, rhs: Cc_Arduino_Cli_Commands_V1_SettingsGetValueRequest) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.valueFormat != rhs.valueFormat {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SettingsGetValueResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SettingsGetValueResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}encoded_value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.encodedValue) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.encodedValue.isEmpty {
      try visitor.visitSingularStringField(value: self.encodedValue, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SettingsGetValueResponse, rhs: Cc_Arduino_Cli_Commands_V1_SettingsGetValueResponse) -> Bool {
    if lhs.encodedValue != rhs.encodedValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SettingsSetValueRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SettingsSetValueRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{3}encoded_value\0\u{3}value_format\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.encodedValue) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.valueFormat) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if !self.encodedValue.isEmpty {
      try visitor.visitSingularStringField(value: self.encodedValue, fieldNumber: 2)
    }
    if !self.valueFormat.isEmpty {
      try visitor.visitSingularStringField(value: self.valueFormat, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SettingsSetValueRequest, rhs: Cc_Arduino_Cli_Commands_V1_SettingsSetValueRequest) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.encodedValue != rhs.encodedValue {return false}
    if lhs.valueFormat != rhs.valueFormat {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SettingsSetValueResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SettingsSetValueResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SettingsSetValueResponse, rhs: Cc_Arduino_Cli_Commands_V1_SettingsSetValueResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SettingsEnumerateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SettingsEnumerateRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SettingsEnumerateRequest, rhs: Cc_Arduino_Cli_Commands_V1_SettingsEnumerateRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SettingsEnumerateResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entries\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse, rhs: Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse) -> Bool {
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse.Entry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse.protoMessageName + ".Entry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.type) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.key.isEmpty {
      try visitor.visitSingularStringField(value: self.key, fieldNumber: 1)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse.Entry, rhs: Cc_Arduino_Cli_Commands_V1_SettingsEnumerateResponse.Entry) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
