// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cc/arduino/cli/commands/v1/board.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This file is part of arduino-cli.
//
// Copyright 2024 ARDUINO SA (https://www.arduino.cc/)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardDetailsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// The fully qualified board name of the board you want information about
  /// (e.g., `arduino:avr:uno`).
  var fqbn: String = String()

  /// If set to true the returned build properties will be left unexpanded, with
  /// the variables placeholders exactly as defined in the platform.
  var doNotExpandBuildProperties: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardDetailsResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The fully qualified board name of the board.
  var fqbn: String {
    get {_storage._fqbn}
    set {_uniqueStorage()._fqbn = newValue}
  }

  /// Name used to identify the board to humans (e.g., Arduino Uno).
  var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// Installed version of the board's platform.
  var version: String {
    get {_storage._version}
    set {_uniqueStorage()._version = newValue}
  }

  /// The board ID component of the FQBN (e.g., `uno`).
  var propertiesID: String {
    get {_storage._propertiesID}
    set {_uniqueStorage()._propertiesID = newValue}
  }

  /// Board alias that can be used as a more user friendly alternative to the
  /// FQBN.
  var alias: String {
    get {_storage._alias}
    set {_uniqueStorage()._alias = newValue}
  }

  /// Whether this is an official or 3rd party board.
  var official: Bool {
    get {_storage._official}
    set {_uniqueStorage()._official = newValue}
  }

  /// URL of the board's pinout documentation.
  var pinout: String {
    get {_storage._pinout}
    set {_uniqueStorage()._pinout = newValue}
  }

  /// Data about the package that contains the board's platform.
  var package: Cc_Arduino_Cli_Commands_V1_Package {
    get {_storage._package ?? Cc_Arduino_Cli_Commands_V1_Package()}
    set {_uniqueStorage()._package = newValue}
  }
  /// Returns true if `package` has been explicitly set.
  var hasPackage: Bool {_storage._package != nil}
  /// Clears the value of `package`. Subsequent reads from it will return its default value.
  mutating func clearPackage() {_uniqueStorage()._package = nil}

  /// Data about the board's platform.
  var platform: Cc_Arduino_Cli_Commands_V1_BoardPlatform {
    get {_storage._platform ?? Cc_Arduino_Cli_Commands_V1_BoardPlatform()}
    set {_uniqueStorage()._platform = newValue}
  }
  /// Returns true if `platform` has been explicitly set.
  var hasPlatform: Bool {_storage._platform != nil}
  /// Clears the value of `platform`. Subsequent reads from it will return its default value.
  mutating func clearPlatform() {_uniqueStorage()._platform = nil}

  /// Tool dependencies of the board.
  var toolsDependencies: [Cc_Arduino_Cli_Commands_V1_ToolsDependencies] {
    get {_storage._toolsDependencies}
    set {_uniqueStorage()._toolsDependencies = newValue}
  }

  /// The board's custom configuration options.
  var configOptions: [Cc_Arduino_Cli_Commands_V1_ConfigOption] {
    get {_storage._configOptions}
    set {_uniqueStorage()._configOptions = newValue}
  }

  /// List of programmers supported by the board.
  var programmers: [Cc_Arduino_Cli_Commands_V1_Programmer] {
    get {_storage._programmers}
    set {_uniqueStorage()._programmers = newValue}
  }

  /// Identifying information for the board (e.g., USB VID/PID).
  var identificationProperties: [Cc_Arduino_Cli_Commands_V1_BoardIdentificationProperties] {
    get {_storage._identificationProperties}
    set {_uniqueStorage()._identificationProperties = newValue}
  }

  /// Board build properties used for compiling.
  var buildProperties: [String] {
    get {_storage._buildProperties}
    set {_uniqueStorage()._buildProperties = newValue}
  }

  /// Default programmer for the board.
  var defaultProgrammerID: String {
    get {_storage._defaultProgrammerID}
    set {_uniqueStorage()._defaultProgrammerID = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardIdentificationProperties: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A set of properties that must all be matched to identify the board.
  var properties: Dictionary<String,String> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_Package: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Maintainer of the package.
  var maintainer: String = String()

  /// The URL of the platforms index file
  /// (e.g., https://downloads.arduino.cc/packages/package_index.json).
  var url: String = String()

  /// A URL provided by the package author, intended to point to their website.
  var websiteURL: String = String()

  /// Email address of the package maintainer.
  var email: String = String()

  /// Package vendor name.
  var name: String = String()

  /// Resources for getting help about using the package.
  var help: Cc_Arduino_Cli_Commands_V1_Help {
    get {_help ?? Cc_Arduino_Cli_Commands_V1_Help()}
    set {_help = newValue}
  }
  /// Returns true if `help` has been explicitly set.
  var hasHelp: Bool {self._help != nil}
  /// Clears the value of `help`. Subsequent reads from it will return its default value.
  mutating func clearHelp() {self._help = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _help: Cc_Arduino_Cli_Commands_V1_Help? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_Help: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// URL for getting online help.
  var online: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardPlatform: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Architecture of the platform (e.g., `avr`).
  var architecture: String = String()

  /// Category of the platform. Set to `Contributed` for 3rd party platforms.
  var category: String = String()

  /// Download URL of the platform archive file.
  var url: String = String()

  /// File name of the platform archive.
  var archiveFilename: String = String()

  /// Checksum of the platform archive.
  var checksum: String = String()

  /// File size of the platform archive.
  var size: Int64 = 0

  /// Name used to identify the platform to humans.
  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ToolsDependencies: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Vendor name of the package containing the tool definition.
  var packager: String = String()

  /// Tool name.
  var name: String = String()

  /// Tool version.
  var version: String = String()

  /// Data for the operating system-specific builds of the tool.
  var systems: [Cc_Arduino_Cli_Commands_V1_Systems] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_Systems: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Checksum of the tool archive.
  var checksum: String = String()

  /// Operating system identifier.
  var host: String = String()

  /// File name of the tool archive.
  var archiveFilename: String = String()

  /// Download URL of the tool archive.
  var url: String = String()

  /// File size of the tool archive.
  var size: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ConfigOption: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ID of the configuration option. For identifying the option to machines.
  var option: String = String()

  /// Name of the configuration option for identifying the option to humans.
  var optionLabel: String = String()

  /// Possible values of the configuration option.
  var values: [Cc_Arduino_Cli_Commands_V1_ConfigValue] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ConfigValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The configuration option value.
  var value: String = String()

  /// Label to identify the configuration option to humans.
  var valueLabel: String = String()

  /// Whether the configuration option is selected.
  var selected: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardListRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Search for boards for the given time (in milliseconds).
  var timeout: Int64 = 0

  /// The fully qualified board name of the board you want information about
  /// (e.g., `arduino:avr:uno`).
  var fqbn: String = String()

  /// If set to true, when a board cannot be identified using the installed
  /// platforms, the cloud API will not be called to detect the board.
  var skipCloudApiForBoardDetection: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardListResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of ports and the boards detected on those ports.
  var ports: [Cc_Arduino_Cli_Commands_V1_DetectedPort] = []

  /// Warning messages or errors coming from the discoveries.
  var warnings: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_DetectedPort: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The possible boards attached to the port.
  var matchingBoards: [Cc_Arduino_Cli_Commands_V1_BoardListItem] = []

  /// The port details.
  var port: Cc_Arduino_Cli_Commands_V1_Port {
    get {_port ?? Cc_Arduino_Cli_Commands_V1_Port()}
    set {_port = newValue}
  }
  /// Returns true if `port` has been explicitly set.
  var hasPort: Bool {self._port != nil}
  /// Clears the value of `port`. Subsequent reads from it will return its default value.
  mutating func clearPort() {self._port = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _port: Cc_Arduino_Cli_Commands_V1_Port? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardListAllRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// The search query to filter the board list by.
  var searchArgs: [String] = []

  /// Set to true to get also the boards marked as "hidden" in the platform.
  var includeHiddenBoards: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardListAllResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of installed boards.
  var boards: [Cc_Arduino_Cli_Commands_V1_BoardListItem] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardListWatchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// If set to true, when a board cannot be identified using the installed
  /// platforms, the cloud API will not be called to detect the board.
  var skipCloudApiForBoardDetection: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardListWatchResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Event type as received from the serial discovery tool.
  var eventType: String = String()

  /// Information about the port.
  var port: Cc_Arduino_Cli_Commands_V1_DetectedPort {
    get {_port ?? Cc_Arduino_Cli_Commands_V1_DetectedPort()}
    set {_port = newValue}
  }
  /// Returns true if `port` has been explicitly set.
  var hasPort: Bool {self._port != nil}
  /// Clears the value of `port`. Subsequent reads from it will return its default value.
  mutating func clearPort() {self._port = nil}

  /// Eventual errors when detecting connected boards.
  var error: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _port: Cc_Arduino_Cli_Commands_V1_DetectedPort? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardListItem: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name for use when identifying the board to a human.
  var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// The fully qualified board name. Used to identify the board to a machine.
  var fqbn: String {
    get {_storage._fqbn}
    set {_uniqueStorage()._fqbn = newValue}
  }

  /// If the board is marked as "hidden" in the platform.
  var isHidden: Bool {
    get {_storage._isHidden}
    set {_uniqueStorage()._isHidden = newValue}
  }

  /// Platform this board belongs to.
  var platform: Cc_Arduino_Cli_Commands_V1_Platform {
    get {_storage._platform ?? Cc_Arduino_Cli_Commands_V1_Platform()}
    set {_uniqueStorage()._platform = newValue}
  }
  /// Returns true if `platform` has been explicitly set.
  var hasPlatform: Bool {_storage._platform != nil}
  /// Clears the value of `platform`. Subsequent reads from it will return its default value.
  mutating func clearPlatform() {_uniqueStorage()._platform = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardSearchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// The search query to filter the board list by.
  var searchArgs: String = String()

  /// Set to true to get also the boards marked as "hidden" in installed
  /// platforms.
  var includeHiddenBoards: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardSearchResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of installed and installable boards.
  var boards: [Cc_Arduino_Cli_Commands_V1_BoardListItem] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardIdentifyRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// A set of properties to search (can be taken from a Port message).
  var properties: Dictionary<String,String> = [:]

  /// If set to true, when a board cannot be identified using the installed
  /// platforms, the cloud API will be called to detect the board.
  var useCloudApiForUnknownBoardDetection: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BoardIdentifyResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of matching boards (they may have an FQBN with options set).
  var boards: [Cc_Arduino_Cli_Commands_V1_BoardListItem] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "cc.arduino.cli.commands.v1"

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardDetailsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardDetailsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0\u{3}do_not_expand_build_properties\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.doNotExpandBuildProperties) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 2)
    }
    if self.doNotExpandBuildProperties != false {
      try visitor.visitSingularBoolField(value: self.doNotExpandBuildProperties, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardDetailsRequest, rhs: Cc_Arduino_Cli_Commands_V1_BoardDetailsRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs.doNotExpandBuildProperties != rhs.doNotExpandBuildProperties {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardDetailsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardDetailsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fqbn\0\u{1}name\0\u{1}version\0\u{3}properties_id\0\u{1}alias\0\u{1}official\0\u{1}pinout\0\u{1}package\0\u{1}platform\0\u{3}tools_dependencies\0\u{3}config_options\0\u{2}\u{2}programmers\0\u{4}\u{2}identification_properties\0\u{3}build_properties\0\u{3}default_programmer_id\0\u{c}\u{e}\u{1}")

  fileprivate class _StorageClass {
    var _fqbn: String = String()
    var _name: String = String()
    var _version: String = String()
    var _propertiesID: String = String()
    var _alias: String = String()
    var _official: Bool = false
    var _pinout: String = String()
    var _package: Cc_Arduino_Cli_Commands_V1_Package? = nil
    var _platform: Cc_Arduino_Cli_Commands_V1_BoardPlatform? = nil
    var _toolsDependencies: [Cc_Arduino_Cli_Commands_V1_ToolsDependencies] = []
    var _configOptions: [Cc_Arduino_Cli_Commands_V1_ConfigOption] = []
    var _programmers: [Cc_Arduino_Cli_Commands_V1_Programmer] = []
    var _identificationProperties: [Cc_Arduino_Cli_Commands_V1_BoardIdentificationProperties] = []
    var _buildProperties: [String] = []
    var _defaultProgrammerID: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _fqbn = source._fqbn
      _name = source._name
      _version = source._version
      _propertiesID = source._propertiesID
      _alias = source._alias
      _official = source._official
      _pinout = source._pinout
      _package = source._package
      _platform = source._platform
      _toolsDependencies = source._toolsDependencies
      _configOptions = source._configOptions
      _programmers = source._programmers
      _identificationProperties = source._identificationProperties
      _buildProperties = source._buildProperties
      _defaultProgrammerID = source._defaultProgrammerID
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._fqbn) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._version) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._propertiesID) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._alias) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._official) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._pinout) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._package) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._platform) }()
        case 10: try { try decoder.decodeRepeatedMessageField(value: &_storage._toolsDependencies) }()
        case 11: try { try decoder.decodeRepeatedMessageField(value: &_storage._configOptions) }()
        case 13: try { try decoder.decodeRepeatedMessageField(value: &_storage._programmers) }()
        case 15: try { try decoder.decodeRepeatedMessageField(value: &_storage._identificationProperties) }()
        case 16: try { try decoder.decodeRepeatedStringField(value: &_storage._buildProperties) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._defaultProgrammerID) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._fqbn.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fqbn, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if !_storage._version.isEmpty {
        try visitor.visitSingularStringField(value: _storage._version, fieldNumber: 3)
      }
      if !_storage._propertiesID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._propertiesID, fieldNumber: 4)
      }
      if !_storage._alias.isEmpty {
        try visitor.visitSingularStringField(value: _storage._alias, fieldNumber: 5)
      }
      if _storage._official != false {
        try visitor.visitSingularBoolField(value: _storage._official, fieldNumber: 6)
      }
      if !_storage._pinout.isEmpty {
        try visitor.visitSingularStringField(value: _storage._pinout, fieldNumber: 7)
      }
      try { if let v = _storage._package {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._platform {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      if !_storage._toolsDependencies.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._toolsDependencies, fieldNumber: 10)
      }
      if !_storage._configOptions.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._configOptions, fieldNumber: 11)
      }
      if !_storage._programmers.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._programmers, fieldNumber: 13)
      }
      if !_storage._identificationProperties.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._identificationProperties, fieldNumber: 15)
      }
      if !_storage._buildProperties.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._buildProperties, fieldNumber: 16)
      }
      if !_storage._defaultProgrammerID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._defaultProgrammerID, fieldNumber: 17)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardDetailsResponse, rhs: Cc_Arduino_Cli_Commands_V1_BoardDetailsResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._fqbn != rhs_storage._fqbn {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._version != rhs_storage._version {return false}
        if _storage._propertiesID != rhs_storage._propertiesID {return false}
        if _storage._alias != rhs_storage._alias {return false}
        if _storage._official != rhs_storage._official {return false}
        if _storage._pinout != rhs_storage._pinout {return false}
        if _storage._package != rhs_storage._package {return false}
        if _storage._platform != rhs_storage._platform {return false}
        if _storage._toolsDependencies != rhs_storage._toolsDependencies {return false}
        if _storage._configOptions != rhs_storage._configOptions {return false}
        if _storage._programmers != rhs_storage._programmers {return false}
        if _storage._identificationProperties != rhs_storage._identificationProperties {return false}
        if _storage._buildProperties != rhs_storage._buildProperties {return false}
        if _storage._defaultProgrammerID != rhs_storage._defaultProgrammerID {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardIdentificationProperties: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardIdentificationProperties"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}properties\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.properties) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.properties.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.properties, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardIdentificationProperties, rhs: Cc_Arduino_Cli_Commands_V1_BoardIdentificationProperties) -> Bool {
    if lhs.properties != rhs.properties {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Package: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Package"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}maintainer\0\u{1}url\0\u{3}website_url\0\u{1}email\0\u{1}name\0\u{1}help\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.maintainer) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.websiteURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.email) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._help) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.maintainer.isEmpty {
      try visitor.visitSingularStringField(value: self.maintainer, fieldNumber: 1)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 2)
    }
    if !self.websiteURL.isEmpty {
      try visitor.visitSingularStringField(value: self.websiteURL, fieldNumber: 3)
    }
    if !self.email.isEmpty {
      try visitor.visitSingularStringField(value: self.email, fieldNumber: 4)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 5)
    }
    try { if let v = self._help {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Package, rhs: Cc_Arduino_Cli_Commands_V1_Package) -> Bool {
    if lhs.maintainer != rhs.maintainer {return false}
    if lhs.url != rhs.url {return false}
    if lhs.websiteURL != rhs.websiteURL {return false}
    if lhs.email != rhs.email {return false}
    if lhs.name != rhs.name {return false}
    if lhs._help != rhs._help {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Help: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Help"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}online\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.online) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.online.isEmpty {
      try visitor.visitSingularStringField(value: self.online, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Help, rhs: Cc_Arduino_Cli_Commands_V1_Help) -> Bool {
    if lhs.online != rhs.online {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardPlatform: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardPlatform"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}architecture\0\u{1}category\0\u{1}url\0\u{3}archive_filename\0\u{1}checksum\0\u{1}size\0\u{1}name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.architecture) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.category) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.archiveFilename) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.checksum) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.size) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.architecture.isEmpty {
      try visitor.visitSingularStringField(value: self.architecture, fieldNumber: 1)
    }
    if !self.category.isEmpty {
      try visitor.visitSingularStringField(value: self.category, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.archiveFilename.isEmpty {
      try visitor.visitSingularStringField(value: self.archiveFilename, fieldNumber: 4)
    }
    if !self.checksum.isEmpty {
      try visitor.visitSingularStringField(value: self.checksum, fieldNumber: 5)
    }
    if self.size != 0 {
      try visitor.visitSingularInt64Field(value: self.size, fieldNumber: 6)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardPlatform, rhs: Cc_Arduino_Cli_Commands_V1_BoardPlatform) -> Bool {
    if lhs.architecture != rhs.architecture {return false}
    if lhs.category != rhs.category {return false}
    if lhs.url != rhs.url {return false}
    if lhs.archiveFilename != rhs.archiveFilename {return false}
    if lhs.checksum != rhs.checksum {return false}
    if lhs.size != rhs.size {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ToolsDependencies: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ToolsDependencies"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}packager\0\u{1}name\0\u{1}version\0\u{1}systems\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.packager) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.systems) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.packager.isEmpty {
      try visitor.visitSingularStringField(value: self.packager, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 3)
    }
    if !self.systems.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.systems, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ToolsDependencies, rhs: Cc_Arduino_Cli_Commands_V1_ToolsDependencies) -> Bool {
    if lhs.packager != rhs.packager {return false}
    if lhs.name != rhs.name {return false}
    if lhs.version != rhs.version {return false}
    if lhs.systems != rhs.systems {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_Systems: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Systems"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}checksum\0\u{1}host\0\u{3}archive_filename\0\u{1}url\0\u{1}size\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.checksum) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.host) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.archiveFilename) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.size) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.checksum.isEmpty {
      try visitor.visitSingularStringField(value: self.checksum, fieldNumber: 1)
    }
    if !self.host.isEmpty {
      try visitor.visitSingularStringField(value: self.host, fieldNumber: 2)
    }
    if !self.archiveFilename.isEmpty {
      try visitor.visitSingularStringField(value: self.archiveFilename, fieldNumber: 3)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 4)
    }
    if self.size != 0 {
      try visitor.visitSingularInt64Field(value: self.size, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_Systems, rhs: Cc_Arduino_Cli_Commands_V1_Systems) -> Bool {
    if lhs.checksum != rhs.checksum {return false}
    if lhs.host != rhs.host {return false}
    if lhs.archiveFilename != rhs.archiveFilename {return false}
    if lhs.url != rhs.url {return false}
    if lhs.size != rhs.size {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ConfigOption: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigOption"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}option\0\u{3}option_label\0\u{1}values\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.option) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.optionLabel) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.option.isEmpty {
      try visitor.visitSingularStringField(value: self.option, fieldNumber: 1)
    }
    if !self.optionLabel.isEmpty {
      try visitor.visitSingularStringField(value: self.optionLabel, fieldNumber: 2)
    }
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ConfigOption, rhs: Cc_Arduino_Cli_Commands_V1_ConfigOption) -> Bool {
    if lhs.option != rhs.option {return false}
    if lhs.optionLabel != rhs.optionLabel {return false}
    if lhs.values != rhs.values {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ConfigValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{3}value_label\0\u{1}selected\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.value) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.valueLabel) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.selected) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 1)
    }
    if !self.valueLabel.isEmpty {
      try visitor.visitSingularStringField(value: self.valueLabel, fieldNumber: 2)
    }
    if self.selected != false {
      try visitor.visitSingularBoolField(value: self.selected, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ConfigValue, rhs: Cc_Arduino_Cli_Commands_V1_ConfigValue) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.valueLabel != rhs.valueLabel {return false}
    if lhs.selected != rhs.selected {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardListRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardListRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}timeout\0\u{1}fqbn\0\u{3}skip_cloud_api_for_board_detection\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.timeout) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.skipCloudApiForBoardDetection) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.timeout != 0 {
      try visitor.visitSingularInt64Field(value: self.timeout, fieldNumber: 2)
    }
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 3)
    }
    if self.skipCloudApiForBoardDetection != false {
      try visitor.visitSingularBoolField(value: self.skipCloudApiForBoardDetection, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardListRequest, rhs: Cc_Arduino_Cli_Commands_V1_BoardListRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.timeout != rhs.timeout {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs.skipCloudApiForBoardDetection != rhs.skipCloudApiForBoardDetection {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardListResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardListResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ports\0\u{1}warnings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.ports) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.warnings) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ports.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.ports, fieldNumber: 1)
    }
    if !self.warnings.isEmpty {
      try visitor.visitRepeatedStringField(value: self.warnings, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardListResponse, rhs: Cc_Arduino_Cli_Commands_V1_BoardListResponse) -> Bool {
    if lhs.ports != rhs.ports {return false}
    if lhs.warnings != rhs.warnings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_DetectedPort: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DetectedPort"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}matching_boards\0\u{1}port\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.matchingBoards) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._port) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.matchingBoards.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.matchingBoards, fieldNumber: 1)
    }
    try { if let v = self._port {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_DetectedPort, rhs: Cc_Arduino_Cli_Commands_V1_DetectedPort) -> Bool {
    if lhs.matchingBoards != rhs.matchingBoards {return false}
    if lhs._port != rhs._port {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardListAllRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardListAllRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{3}search_args\0\u{3}include_hidden_boards\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.searchArgs) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.includeHiddenBoards) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.searchArgs.isEmpty {
      try visitor.visitRepeatedStringField(value: self.searchArgs, fieldNumber: 2)
    }
    if self.includeHiddenBoards != false {
      try visitor.visitSingularBoolField(value: self.includeHiddenBoards, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardListAllRequest, rhs: Cc_Arduino_Cli_Commands_V1_BoardListAllRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.searchArgs != rhs.searchArgs {return false}
    if lhs.includeHiddenBoards != rhs.includeHiddenBoards {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardListAllResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardListAllResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}boards\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.boards) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.boards.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.boards, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardListAllResponse, rhs: Cc_Arduino_Cli_Commands_V1_BoardListAllResponse) -> Bool {
    if lhs.boards != rhs.boards {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardListWatchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardListWatchRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{3}skip_cloud_api_for_board_detection\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.skipCloudApiForBoardDetection) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.skipCloudApiForBoardDetection != false {
      try visitor.visitSingularBoolField(value: self.skipCloudApiForBoardDetection, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardListWatchRequest, rhs: Cc_Arduino_Cli_Commands_V1_BoardListWatchRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.skipCloudApiForBoardDetection != rhs.skipCloudApiForBoardDetection {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardListWatchResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardListWatchResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}event_type\0\u{1}port\0\u{1}error\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.eventType) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._port) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.error) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.eventType.isEmpty {
      try visitor.visitSingularStringField(value: self.eventType, fieldNumber: 1)
    }
    try { if let v = self._port {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.error.isEmpty {
      try visitor.visitSingularStringField(value: self.error, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardListWatchResponse, rhs: Cc_Arduino_Cli_Commands_V1_BoardListWatchResponse) -> Bool {
    if lhs.eventType != rhs.eventType {return false}
    if lhs._port != rhs._port {return false}
    if lhs.error != rhs.error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardListItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardListItem"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}fqbn\0\u{3}is_hidden\0\u{2}\u{3}platform\0")

  fileprivate class _StorageClass {
    var _name: String = String()
    var _fqbn: String = String()
    var _isHidden: Bool = false
    var _platform: Cc_Arduino_Cli_Commands_V1_Platform? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _fqbn = source._fqbn
      _isHidden = source._isHidden
      _platform = source._platform
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._fqbn) }()
        case 3: try { try decoder.decodeSingularBoolField(value: &_storage._isHidden) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._platform) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 1)
      }
      if !_storage._fqbn.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fqbn, fieldNumber: 2)
      }
      if _storage._isHidden != false {
        try visitor.visitSingularBoolField(value: _storage._isHidden, fieldNumber: 3)
      }
      try { if let v = _storage._platform {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardListItem, rhs: Cc_Arduino_Cli_Commands_V1_BoardListItem) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._fqbn != rhs_storage._fqbn {return false}
        if _storage._isHidden != rhs_storage._isHidden {return false}
        if _storage._platform != rhs_storage._platform {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardSearchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardSearchRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{3}search_args\0\u{3}include_hidden_boards\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.searchArgs) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.includeHiddenBoards) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.searchArgs.isEmpty {
      try visitor.visitSingularStringField(value: self.searchArgs, fieldNumber: 2)
    }
    if self.includeHiddenBoards != false {
      try visitor.visitSingularBoolField(value: self.includeHiddenBoards, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardSearchRequest, rhs: Cc_Arduino_Cli_Commands_V1_BoardSearchRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.searchArgs != rhs.searchArgs {return false}
    if lhs.includeHiddenBoards != rhs.includeHiddenBoards {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardSearchResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardSearchResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}boards\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.boards) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.boards.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.boards, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardSearchResponse, rhs: Cc_Arduino_Cli_Commands_V1_BoardSearchResponse) -> Bool {
    if lhs.boards != rhs.boards {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardIdentifyRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardIdentifyRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}properties\0\u{3}use_cloud_api_for_unknown_board_detection\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.properties) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.useCloudApiForUnknownBoardDetection) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.properties.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.properties, fieldNumber: 2)
    }
    if self.useCloudApiForUnknownBoardDetection != false {
      try visitor.visitSingularBoolField(value: self.useCloudApiForUnknownBoardDetection, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardIdentifyRequest, rhs: Cc_Arduino_Cli_Commands_V1_BoardIdentifyRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.properties != rhs.properties {return false}
    if lhs.useCloudApiForUnknownBoardDetection != rhs.useCloudApiForUnknownBoardDetection {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BoardIdentifyResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BoardIdentifyResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}boards\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.boards) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.boards.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.boards, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BoardIdentifyResponse, rhs: Cc_Arduino_Cli_Commands_V1_BoardIdentifyResponse) -> Bool {
    if lhs.boards != rhs.boards {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
