// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cc/arduino/cli/commands/v1/compile.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This file is part of arduino-cli.
//
// Copyright 2024 ARDUINO SA (https://www.arduino.cc/)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_CompileRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_storage._instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_uniqueStorage()._instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {_storage._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {_uniqueStorage()._instance = nil}

  /// Fully Qualified Board Name, e.g.: `arduino:avr:uno`. If this field is
  /// not defined, the FQBN of the board attached to the sketch via the
  /// `BoardAttach` method is used.
  var fqbn: String {
    get {_storage._fqbn}
    set {_uniqueStorage()._fqbn = newValue}
  }

  /// The path where the sketch is stored.
  var sketchPath: String {
    get {_storage._sketchPath}
    set {_uniqueStorage()._sketchPath = newValue}
  }

  /// Just get the build properties and do not run the full compile.
  var showProperties: Bool {
    get {_storage._showProperties}
    set {_uniqueStorage()._showProperties = newValue}
  }

  /// Print preprocessed code to stdout instead of compiling.
  var preprocess: Bool {
    get {_storage._preprocess}
    set {_uniqueStorage()._preprocess = newValue}
  }

  /// Builds of core and sketches are saved into this path to be cached and
  /// reused.
  ///
  /// NOTE: This field was marked as deprecated in the .proto file.
  var buildCachePath: String {
    get {_storage._buildCachePath}
    set {_uniqueStorage()._buildCachePath = newValue}
  }

  /// Path to use to store the files used for the compilation. If omitted,
  /// a directory will be created in the operating system's default temporary
  /// path.
  var buildPath: String {
    get {_storage._buildPath}
    set {_uniqueStorage()._buildPath = newValue}
  }

  /// List of custom build properties.
  var buildProperties: [String] {
    get {_storage._buildProperties}
    set {_uniqueStorage()._buildProperties = newValue}
  }

  /// Used to tell gcc which warning level to use. The level names are: "none",
  /// "default", "more" and "all".
  var warnings: String {
    get {_storage._warnings}
    set {_uniqueStorage()._warnings = newValue}
  }

  /// Turns on verbose mode.
  var verbose: Bool {
    get {_storage._verbose}
    set {_uniqueStorage()._verbose = newValue}
  }

  /// Suppresses almost every output.
  var quiet: Bool {
    get {_storage._quiet}
    set {_uniqueStorage()._quiet = newValue}
  }

  /// The max number of concurrent compiler instances to run (as `make -jx`).
  /// If jobs is set to 0, it will use the number of available CPUs as the
  /// maximum.
  var jobs: Int32 {
    get {_storage._jobs}
    set {_uniqueStorage()._jobs = newValue}
  }

  /// A list of paths to directories containing a collection of libraries.
  var libraries: [String] {
    get {_storage._libraries}
    set {_uniqueStorage()._libraries = newValue}
  }

  /// Optimize compile output for debug, not for release.
  var optimizeForDebug: Bool {
    get {_storage._optimizeForDebug}
    set {_uniqueStorage()._optimizeForDebug = newValue}
  }

  /// Optional: save the build artifacts in this directory, the directory must
  /// exist.
  var exportDir: String {
    get {_storage._exportDir}
    set {_uniqueStorage()._exportDir = newValue}
  }

  /// Optional: cleanup the build folder and do not use any previously cached
  /// build.
  var clean: Bool {
    get {_storage._clean}
    set {_uniqueStorage()._clean = newValue}
  }

  /// When set to `true` only the compilation database will be produced and no
  /// actual build will be performed.
  var createCompilationDatabaseOnly: Bool {
    get {_storage._createCompilationDatabaseOnly}
    set {_uniqueStorage()._createCompilationDatabaseOnly = newValue}
  }

  /// This map (source file -> new content) let the builder use the provided
  /// content instead of reading the corresponding file on disk. This is useful
  /// for IDE that have unsaved changes in memory. The path must be relative to
  /// the sketch directory. Only files from the sketch are allowed.
  var sourceOverride: Dictionary<String,String> {
    get {_storage._sourceOverride}
    set {_uniqueStorage()._sourceOverride = newValue}
  }

  /// When set to `true` the compiled binary will be copied to the export
  /// directory.
  var exportBinaries: Bool {
    get {_storage._exportBinaries ?? false}
    set {_uniqueStorage()._exportBinaries = newValue}
  }
  /// Returns true if `exportBinaries` has been explicitly set.
  var hasExportBinaries: Bool {_storage._exportBinaries != nil}
  /// Clears the value of `exportBinaries`. Subsequent reads from it will return its default value.
  mutating func clearExportBinaries() {_uniqueStorage()._exportBinaries = nil}

  /// A list of paths to single libraries root directory.
  var library: [String] {
    get {_storage._library}
    set {_uniqueStorage()._library = newValue}
  }

  /// The path where to search for the custom signing key name and the encrypt
  /// key name.
  var keysKeychain: String {
    get {_storage._keysKeychain}
    set {_uniqueStorage()._keysKeychain = newValue}
  }

  /// The name of the custom key to use for signing during the compile process.
  var signKey: String {
    get {_storage._signKey}
    set {_uniqueStorage()._signKey = newValue}
  }

  /// The name of the custom key to use for encrypting during the compile process.
  var encryptKey: String {
    get {_storage._encryptKey}
    set {_uniqueStorage()._encryptKey = newValue}
  }

  /// If set to true the build will skip the library discovery process and will
  /// use the same libraries of latest build. Enabling this flag may produce a
  /// wrong output and should not be used in regular compiles unless there is a
  /// very specific reason to do so. This flag is mainly provided for usage in
  /// language servers to optimize the build speed in some particular cases.
  var skipLibrariesDiscovery: Bool {
    get {_storage._skipLibrariesDiscovery}
    set {_uniqueStorage()._skipLibrariesDiscovery = newValue}
  }

  /// If set to true the returned build properties will be left unexpanded, with
  /// the variables placeholders exactly as defined in the platform.
  var doNotExpandBuildProperties: Bool {
    get {_storage._doNotExpandBuildProperties}
    set {_uniqueStorage()._doNotExpandBuildProperties = newValue}
  }

  /// Search for precompiled cores in the given paths and use them if found.
  /// This search is performed after the standard build_cache directory.
  var buildCacheExtraPaths: [String] {
    get {_storage._buildCacheExtraPaths}
    set {_uniqueStorage()._buildCacheExtraPaths = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_CompileResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_CompileResponse.OneOf_Message? = nil

  /// The output of the compilation process (stream).
  var outStream: Data {
    get {
      if case .outStream(let v)? = message {return v}
      return Data()
    }
    set {message = .outStream(newValue)}
  }

  /// The error output of the compilation process (stream).
  var errStream: Data {
    get {
      if case .errStream(let v)? = message {return v}
      return Data()
    }
    set {message = .errStream(newValue)}
  }

  /// Completions reports of the compilation process (stream).
  var progress: Cc_Arduino_Cli_Commands_V1_TaskProgress {
    get {
      if case .progress(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_TaskProgress()
    }
    set {message = .progress(newValue)}
  }

  /// The compilation result.
  var result: Cc_Arduino_Cli_Commands_V1_BuilderResult {
    get {
      if case .result(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_BuilderResult()
    }
    set {message = .result(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// The output of the compilation process (stream).
    case outStream(Data)
    /// The error output of the compilation process (stream).
    case errStream(Data)
    /// Completions reports of the compilation process (stream).
    case progress(Cc_Arduino_Cli_Commands_V1_TaskProgress)
    /// The compilation result.
    case result(Cc_Arduino_Cli_Commands_V1_BuilderResult)

  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_InstanceNeedsReinitializationError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BuilderResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The compiler build path.
  var buildPath: String = String()

  /// The libraries used in the build.
  var usedLibraries: [Cc_Arduino_Cli_Commands_V1_Library] = []

  /// The size of the executable split by sections.
  var executableSectionsSize: [Cc_Arduino_Cli_Commands_V1_ExecutableSectionSize] = []

  /// The platform where the board is defined.
  var boardPlatform: Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference {
    get {_boardPlatform ?? Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference()}
    set {_boardPlatform = newValue}
  }
  /// Returns true if `boardPlatform` has been explicitly set.
  var hasBoardPlatform: Bool {self._boardPlatform != nil}
  /// Clears the value of `boardPlatform`. Subsequent reads from it will return its default value.
  mutating func clearBoardPlatform() {self._boardPlatform = nil}

  /// The platform used for the build (if referenced from the board platform).
  var buildPlatform: Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference {
    get {_buildPlatform ?? Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference()}
    set {_buildPlatform = newValue}
  }
  /// Returns true if `buildPlatform` has been explicitly set.
  var hasBuildPlatform: Bool {self._buildPlatform != nil}
  /// Clears the value of `buildPlatform`. Subsequent reads from it will return its default value.
  mutating func clearBuildPlatform() {self._buildPlatform = nil}

  /// Build properties used for compiling.
  var buildProperties: [String] = []

  /// Compiler errors and warnings.
  var diagnostics: [Cc_Arduino_Cli_Commands_V1_CompileDiagnostic] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _boardPlatform: Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference? = nil
  fileprivate var _buildPlatform: Cc_Arduino_Cli_Commands_V1_InstalledPlatformReference? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ExecutableSectionSize: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the section.
  var name: String = String()

  /// The used size of the section in bytes.
  var size: Int64 = 0

  /// The maximum size of the section in bytes.
  var maxSize: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_CompileDiagnostic: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Severity of the diagnostic.
  var severity: String = String()

  /// The explanation of the diagnostic (it may be multiple preformatted lines).
  var message: String = String()

  /// The file containing the diagnostic.
  var file: String = String()

  /// The line of the diagnostic if available (starts from 1).
  var line: Int64 = 0

  /// The column of the diagnostic if available (starts from 1).
  var column: Int64 = 0

  /// The context where this diagnostic is found (it may be multiple files that
  /// represents a chain of includes, or a text describing where the diagnostic
  /// is found).
  var context: [Cc_Arduino_Cli_Commands_V1_CompileDiagnosticContext] = []

  /// Annotations or suggestions to the diagnostic made by the compiler.
  var notes: [Cc_Arduino_Cli_Commands_V1_CompileDiagnosticNote] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_CompileDiagnosticContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The message describing the context reference.
  var message: String = String()

  /// The file of the context reference.
  var file: String = String()

  /// The line of the context reference.
  var line: Int64 = 0

  /// The column of the context reference.
  var column: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_CompileDiagnosticNote: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The message describing the compiler note.
  var message: String = String()

  /// The file of the compiler note.
  var file: String = String()

  /// The line of the compiler note.
  var line: Int64 = 0

  /// The column of the compiler note.
  var column: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "cc.arduino.cli.commands.v1"

nonisolated extension Cc_Arduino_Cli_Commands_V1_CompileRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompileRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0\u{3}sketch_path\0\u{3}show_properties\0\u{1}preprocess\0\u{3}build_cache_path\0\u{3}build_path\0\u{3}build_properties\0\u{1}warnings\0\u{1}verbose\0\u{1}quiet\0\u{2}\u{3}jobs\0\u{1}libraries\0\u{3}optimize_for_debug\0\u{4}\u{2}export_dir\0\u{1}clean\0\u{4}\u{2}create_compilation_database_only\0\u{3}source_override\0\u{3}export_binaries\0\u{1}library\0\u{3}keys_keychain\0\u{3}sign_key\0\u{3}encrypt_key\0\u{3}skip_libraries_discovery\0\u{3}do_not_expand_build_properties\0\u{3}build_cache_extra_paths\0")

  fileprivate class _StorageClass {
    var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
    var _fqbn: String = String()
    var _sketchPath: String = String()
    var _showProperties: Bool = false
    var _preprocess: Bool = false
    var _buildCachePath: String = String()
    var _buildPath: String = String()
    var _buildProperties: [String] = []
    var _warnings: String = String()
    var _verbose: Bool = false
    var _quiet: Bool = false
    var _jobs: Int32 = 0
    var _libraries: [String] = []
    var _optimizeForDebug: Bool = false
    var _exportDir: String = String()
    var _clean: Bool = false
    var _createCompilationDatabaseOnly: Bool = false
    var _sourceOverride: Dictionary<String,String> = [:]
    var _exportBinaries: Bool? = nil
    var _library: [String] = []
    var _keysKeychain: String = String()
    var _signKey: String = String()
    var _encryptKey: String = String()
    var _skipLibrariesDiscovery: Bool = false
    var _doNotExpandBuildProperties: Bool = false
    var _buildCacheExtraPaths: [String] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _instance = source._instance
      _fqbn = source._fqbn
      _sketchPath = source._sketchPath
      _showProperties = source._showProperties
      _preprocess = source._preprocess
      _buildCachePath = source._buildCachePath
      _buildPath = source._buildPath
      _buildProperties = source._buildProperties
      _warnings = source._warnings
      _verbose = source._verbose
      _quiet = source._quiet
      _jobs = source._jobs
      _libraries = source._libraries
      _optimizeForDebug = source._optimizeForDebug
      _exportDir = source._exportDir
      _clean = source._clean
      _createCompilationDatabaseOnly = source._createCompilationDatabaseOnly
      _sourceOverride = source._sourceOverride
      _exportBinaries = source._exportBinaries
      _library = source._library
      _keysKeychain = source._keysKeychain
      _signKey = source._signKey
      _encryptKey = source._encryptKey
      _skipLibrariesDiscovery = source._skipLibrariesDiscovery
      _doNotExpandBuildProperties = source._doNotExpandBuildProperties
      _buildCacheExtraPaths = source._buildCacheExtraPaths
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._instance) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._fqbn) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._sketchPath) }()
        case 4: try { try decoder.decodeSingularBoolField(value: &_storage._showProperties) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._preprocess) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._buildCachePath) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._buildPath) }()
        case 8: try { try decoder.decodeRepeatedStringField(value: &_storage._buildProperties) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._warnings) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._verbose) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._quiet) }()
        case 14: try { try decoder.decodeSingularInt32Field(value: &_storage._jobs) }()
        case 15: try { try decoder.decodeRepeatedStringField(value: &_storage._libraries) }()
        case 16: try { try decoder.decodeSingularBoolField(value: &_storage._optimizeForDebug) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._exportDir) }()
        case 19: try { try decoder.decodeSingularBoolField(value: &_storage._clean) }()
        case 21: try { try decoder.decodeSingularBoolField(value: &_storage._createCompilationDatabaseOnly) }()
        case 22: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._sourceOverride) }()
        case 23: try { try decoder.decodeSingularBoolField(value: &_storage._exportBinaries) }()
        case 24: try { try decoder.decodeRepeatedStringField(value: &_storage._library) }()
        case 25: try { try decoder.decodeSingularStringField(value: &_storage._keysKeychain) }()
        case 26: try { try decoder.decodeSingularStringField(value: &_storage._signKey) }()
        case 27: try { try decoder.decodeSingularStringField(value: &_storage._encryptKey) }()
        case 28: try { try decoder.decodeSingularBoolField(value: &_storage._skipLibrariesDiscovery) }()
        case 29: try { try decoder.decodeSingularBoolField(value: &_storage._doNotExpandBuildProperties) }()
        case 30: try { try decoder.decodeRepeatedStringField(value: &_storage._buildCacheExtraPaths) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._instance {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._fqbn.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fqbn, fieldNumber: 2)
      }
      if !_storage._sketchPath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._sketchPath, fieldNumber: 3)
      }
      if _storage._showProperties != false {
        try visitor.visitSingularBoolField(value: _storage._showProperties, fieldNumber: 4)
      }
      if _storage._preprocess != false {
        try visitor.visitSingularBoolField(value: _storage._preprocess, fieldNumber: 5)
      }
      if !_storage._buildCachePath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._buildCachePath, fieldNumber: 6)
      }
      if !_storage._buildPath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._buildPath, fieldNumber: 7)
      }
      if !_storage._buildProperties.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._buildProperties, fieldNumber: 8)
      }
      if !_storage._warnings.isEmpty {
        try visitor.visitSingularStringField(value: _storage._warnings, fieldNumber: 9)
      }
      if _storage._verbose != false {
        try visitor.visitSingularBoolField(value: _storage._verbose, fieldNumber: 10)
      }
      if _storage._quiet != false {
        try visitor.visitSingularBoolField(value: _storage._quiet, fieldNumber: 11)
      }
      if _storage._jobs != 0 {
        try visitor.visitSingularInt32Field(value: _storage._jobs, fieldNumber: 14)
      }
      if !_storage._libraries.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._libraries, fieldNumber: 15)
      }
      if _storage._optimizeForDebug != false {
        try visitor.visitSingularBoolField(value: _storage._optimizeForDebug, fieldNumber: 16)
      }
      if !_storage._exportDir.isEmpty {
        try visitor.visitSingularStringField(value: _storage._exportDir, fieldNumber: 18)
      }
      if _storage._clean != false {
        try visitor.visitSingularBoolField(value: _storage._clean, fieldNumber: 19)
      }
      if _storage._createCompilationDatabaseOnly != false {
        try visitor.visitSingularBoolField(value: _storage._createCompilationDatabaseOnly, fieldNumber: 21)
      }
      if !_storage._sourceOverride.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._sourceOverride, fieldNumber: 22)
      }
      try { if let v = _storage._exportBinaries {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 23)
      } }()
      if !_storage._library.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._library, fieldNumber: 24)
      }
      if !_storage._keysKeychain.isEmpty {
        try visitor.visitSingularStringField(value: _storage._keysKeychain, fieldNumber: 25)
      }
      if !_storage._signKey.isEmpty {
        try visitor.visitSingularStringField(value: _storage._signKey, fieldNumber: 26)
      }
      if !_storage._encryptKey.isEmpty {
        try visitor.visitSingularStringField(value: _storage._encryptKey, fieldNumber: 27)
      }
      if _storage._skipLibrariesDiscovery != false {
        try visitor.visitSingularBoolField(value: _storage._skipLibrariesDiscovery, fieldNumber: 28)
      }
      if _storage._doNotExpandBuildProperties != false {
        try visitor.visitSingularBoolField(value: _storage._doNotExpandBuildProperties, fieldNumber: 29)
      }
      if !_storage._buildCacheExtraPaths.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._buildCacheExtraPaths, fieldNumber: 30)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_CompileRequest, rhs: Cc_Arduino_Cli_Commands_V1_CompileRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._instance != rhs_storage._instance {return false}
        if _storage._fqbn != rhs_storage._fqbn {return false}
        if _storage._sketchPath != rhs_storage._sketchPath {return false}
        if _storage._showProperties != rhs_storage._showProperties {return false}
        if _storage._preprocess != rhs_storage._preprocess {return false}
        if _storage._buildCachePath != rhs_storage._buildCachePath {return false}
        if _storage._buildPath != rhs_storage._buildPath {return false}
        if _storage._buildProperties != rhs_storage._buildProperties {return false}
        if _storage._warnings != rhs_storage._warnings {return false}
        if _storage._verbose != rhs_storage._verbose {return false}
        if _storage._quiet != rhs_storage._quiet {return false}
        if _storage._jobs != rhs_storage._jobs {return false}
        if _storage._libraries != rhs_storage._libraries {return false}
        if _storage._optimizeForDebug != rhs_storage._optimizeForDebug {return false}
        if _storage._exportDir != rhs_storage._exportDir {return false}
        if _storage._clean != rhs_storage._clean {return false}
        if _storage._createCompilationDatabaseOnly != rhs_storage._createCompilationDatabaseOnly {return false}
        if _storage._sourceOverride != rhs_storage._sourceOverride {return false}
        if _storage._exportBinaries != rhs_storage._exportBinaries {return false}
        if _storage._library != rhs_storage._library {return false}
        if _storage._keysKeychain != rhs_storage._keysKeychain {return false}
        if _storage._signKey != rhs_storage._signKey {return false}
        if _storage._encryptKey != rhs_storage._encryptKey {return false}
        if _storage._skipLibrariesDiscovery != rhs_storage._skipLibrariesDiscovery {return false}
        if _storage._doNotExpandBuildProperties != rhs_storage._doNotExpandBuildProperties {return false}
        if _storage._buildCacheExtraPaths != rhs_storage._buildCacheExtraPaths {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_CompileResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompileResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}out_stream\0\u{3}err_stream\0\u{1}progress\0\u{1}result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .outStream(v)
        }
      }()
      case 2: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .errStream(v)
        }
      }()
      case 3: try {
        var v: Cc_Arduino_Cli_Commands_V1_TaskProgress?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .progress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .progress(v)
        }
      }()
      case 4: try {
        var v: Cc_Arduino_Cli_Commands_V1_BuilderResult?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .result(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .result(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .outStream?: try {
      guard case .outStream(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    }()
    case .errStream?: try {
      guard case .errStream(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    }()
    case .progress?: try {
      guard case .progress(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .result?: try {
      guard case .result(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_CompileResponse, rhs: Cc_Arduino_Cli_Commands_V1_CompileResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_InstanceNeedsReinitializationError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".InstanceNeedsReinitializationError"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_InstanceNeedsReinitializationError, rhs: Cc_Arduino_Cli_Commands_V1_InstanceNeedsReinitializationError) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BuilderResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BuilderResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}build_path\0\u{3}used_libraries\0\u{3}executable_sections_size\0\u{3}board_platform\0\u{3}build_platform\0\u{4}\u{2}build_properties\0\u{1}diagnostics\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.buildPath) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.usedLibraries) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.executableSectionsSize) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._boardPlatform) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._buildPlatform) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.buildProperties) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.diagnostics) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.buildPath.isEmpty {
      try visitor.visitSingularStringField(value: self.buildPath, fieldNumber: 1)
    }
    if !self.usedLibraries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.usedLibraries, fieldNumber: 2)
    }
    if !self.executableSectionsSize.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.executableSectionsSize, fieldNumber: 3)
    }
    try { if let v = self._boardPlatform {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._buildPlatform {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.buildProperties.isEmpty {
      try visitor.visitRepeatedStringField(value: self.buildProperties, fieldNumber: 7)
    }
    if !self.diagnostics.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.diagnostics, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BuilderResult, rhs: Cc_Arduino_Cli_Commands_V1_BuilderResult) -> Bool {
    if lhs.buildPath != rhs.buildPath {return false}
    if lhs.usedLibraries != rhs.usedLibraries {return false}
    if lhs.executableSectionsSize != rhs.executableSectionsSize {return false}
    if lhs._boardPlatform != rhs._boardPlatform {return false}
    if lhs._buildPlatform != rhs._buildPlatform {return false}
    if lhs.buildProperties != rhs.buildProperties {return false}
    if lhs.diagnostics != rhs.diagnostics {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ExecutableSectionSize: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ExecutableSectionSize"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}size\0\u{3}max_size\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.size) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.maxSize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.size != 0 {
      try visitor.visitSingularInt64Field(value: self.size, fieldNumber: 2)
    }
    if self.maxSize != 0 {
      try visitor.visitSingularInt64Field(value: self.maxSize, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ExecutableSectionSize, rhs: Cc_Arduino_Cli_Commands_V1_ExecutableSectionSize) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.size != rhs.size {return false}
    if lhs.maxSize != rhs.maxSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_CompileDiagnostic: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompileDiagnostic"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}severity\0\u{1}message\0\u{1}file\0\u{1}line\0\u{1}column\0\u{1}context\0\u{1}notes\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.severity) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.file) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.line) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.column) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.context) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.notes) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.severity.isEmpty {
      try visitor.visitSingularStringField(value: self.severity, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.file.isEmpty {
      try visitor.visitSingularStringField(value: self.file, fieldNumber: 3)
    }
    if self.line != 0 {
      try visitor.visitSingularInt64Field(value: self.line, fieldNumber: 4)
    }
    if self.column != 0 {
      try visitor.visitSingularInt64Field(value: self.column, fieldNumber: 5)
    }
    if !self.context.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.context, fieldNumber: 6)
    }
    if !self.notes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.notes, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_CompileDiagnostic, rhs: Cc_Arduino_Cli_Commands_V1_CompileDiagnostic) -> Bool {
    if lhs.severity != rhs.severity {return false}
    if lhs.message != rhs.message {return false}
    if lhs.file != rhs.file {return false}
    if lhs.line != rhs.line {return false}
    if lhs.column != rhs.column {return false}
    if lhs.context != rhs.context {return false}
    if lhs.notes != rhs.notes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_CompileDiagnosticContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompileDiagnosticContext"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}message\0\u{1}file\0\u{1}line\0\u{1}column\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.file) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.line) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.column) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 1)
    }
    if !self.file.isEmpty {
      try visitor.visitSingularStringField(value: self.file, fieldNumber: 2)
    }
    if self.line != 0 {
      try visitor.visitSingularInt64Field(value: self.line, fieldNumber: 3)
    }
    if self.column != 0 {
      try visitor.visitSingularInt64Field(value: self.column, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_CompileDiagnosticContext, rhs: Cc_Arduino_Cli_Commands_V1_CompileDiagnosticContext) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.file != rhs.file {return false}
    if lhs.line != rhs.line {return false}
    if lhs.column != rhs.column {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_CompileDiagnosticNote: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CompileDiagnosticNote"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}message\0\u{1}file\0\u{1}line\0\u{1}column\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.file) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.line) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.column) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 1)
    }
    if !self.file.isEmpty {
      try visitor.visitSingularStringField(value: self.file, fieldNumber: 2)
    }
    if self.line != 0 {
      try visitor.visitSingularInt64Field(value: self.line, fieldNumber: 3)
    }
    if self.column != 0 {
      try visitor.visitSingularInt64Field(value: self.column, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_CompileDiagnosticNote, rhs: Cc_Arduino_Cli_Commands_V1_CompileDiagnosticNote) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.file != rhs.file {return false}
    if lhs.line != rhs.line {return false}
    if lhs.column != rhs.column {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
