// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cc/arduino/cli/commands/v1/core.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This file is part of arduino-cli.
//
// Copyright 2024 ARDUINO SA (https://www.arduino.cc/)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformInstallRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Vendor name of the platform (e.g., `arduino`).
  var platformPackage: String = String()

  /// Architecture name of the platform (e.g., `avr`).
  var architecture: String = String()

  /// Platform version to install.
  var version: String = String()

  /// Set to true to not run (eventual) post install scripts for trusted
  /// platforms.
  var skipPostInstall: Bool = false

  /// Set to true to skip installation if a different version of the platform
  /// is already installed.
  var noOverwrite: Bool = false

  /// Set to true to not run (eventual) pre uninstall scripts for trusted
  /// platforms when performing platform upgrades.
  var skipPreUninstall: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.OneOf_Message? = nil

  /// Progress of the downloads of the platform and tool files.
  var progress: Cc_Arduino_Cli_Commands_V1_DownloadProgress {
    get {
      if case .progress(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_DownloadProgress()
    }
    set {message = .progress(newValue)}
  }

  /// Description of the current stage of the installation.
  var taskProgress: Cc_Arduino_Cli_Commands_V1_TaskProgress {
    get {
      if case .taskProgress(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_TaskProgress()
    }
    set {message = .taskProgress(newValue)}
  }

  /// The installation result.
  var result: Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.Result {
    get {
      if case .result(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.Result()
    }
    set {message = .result(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// Progress of the downloads of the platform and tool files.
    case progress(Cc_Arduino_Cli_Commands_V1_DownloadProgress)
    /// Description of the current stage of the installation.
    case taskProgress(Cc_Arduino_Cli_Commands_V1_TaskProgress)
    /// The installation result.
    case result(Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.Result)

  }

  /// Empty message, reserved for future expansion.
  nonisolated struct Result: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformLoadingError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformDownloadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Vendor name of the platform (e.g., `arduino`).
  var platformPackage: String = String()

  /// Architecture name of the platform (e.g., `avr`).
  var architecture: String = String()

  /// Platform version to download.
  var version: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.OneOf_Message? = nil

  /// Progress of the downloads of platform and tool files.
  var progress: Cc_Arduino_Cli_Commands_V1_DownloadProgress {
    get {
      if case .progress(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_DownloadProgress()
    }
    set {message = .progress(newValue)}
  }

  /// The download result.
  var result: Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.Result {
    get {
      if case .result(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.Result()
    }
    set {message = .result(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// Progress of the downloads of platform and tool files.
    case progress(Cc_Arduino_Cli_Commands_V1_DownloadProgress)
    /// The download result.
    case result(Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.Result)

  }

  /// Empty message, reserved for future expansion.
  nonisolated struct Result: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformUninstallRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Vendor name of the platform (e.g., `arduino`).
  var platformPackage: String = String()

  /// Architecture name of the platform (e.g., `avr`).
  var architecture: String = String()

  /// Set to true to not run (eventual) pre uninstall scripts for trusted
  /// platforms.
  var skipPreUninstall: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.OneOf_Message? = nil

  /// Description of the current stage of the uninstall.
  var taskProgress: Cc_Arduino_Cli_Commands_V1_TaskProgress {
    get {
      if case .taskProgress(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_TaskProgress()
    }
    set {message = .taskProgress(newValue)}
  }

  /// The uninstall result.
  var result: Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.Result {
    get {
      if case .result(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.Result()
    }
    set {message = .result(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// Description of the current stage of the uninstall.
    case taskProgress(Cc_Arduino_Cli_Commands_V1_TaskProgress)
    /// The uninstall result.
    case result(Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.Result)

  }

  /// Empty message, reserved for future expansion.
  nonisolated struct Result: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  init() {}
}

/// AlreadyAtLatestVersionError is returned when an upgrade is not possible
/// because already at latest version.
nonisolated struct Cc_Arduino_Cli_Commands_V1_AlreadyAtLatestVersionError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformUpgradeRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Vendor name of the platform (e.g., `arduino`).
  var platformPackage: String = String()

  /// Architecture name of the platform (e.g., `avr`).
  var architecture: String = String()

  /// Set to true to not run (eventual) post install scripts for trusted
  /// platforms.
  var skipPostInstall: Bool = false

  /// Set to true to not run (eventual) pre uninstall scripts for trusted
  /// platforms when performing platform upgrades.
  var skipPreUninstall: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.OneOf_Message? = nil

  /// Progress of the downloads of the platform and tool files.
  var progress: Cc_Arduino_Cli_Commands_V1_DownloadProgress {
    get {
      if case .progress(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_DownloadProgress()
    }
    set {message = .progress(newValue)}
  }

  /// Description of the current stage of the upgrade.
  var taskProgress: Cc_Arduino_Cli_Commands_V1_TaskProgress {
    get {
      if case .taskProgress(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_TaskProgress()
    }
    set {message = .taskProgress(newValue)}
  }

  /// The upgrade result.
  var result: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.Result {
    get {
      if case .result(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.Result()
    }
    set {message = .result(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// Progress of the downloads of the platform and tool files.
    case progress(Cc_Arduino_Cli_Commands_V1_DownloadProgress)
    /// Description of the current stage of the upgrade.
    case taskProgress(Cc_Arduino_Cli_Commands_V1_TaskProgress)
    /// The upgrade result.
    case result(Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.Result)

  }

  nonisolated struct Result: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// The upgraded platform.
    var platform: Cc_Arduino_Cli_Commands_V1_Platform {
      get {_platform ?? Cc_Arduino_Cli_Commands_V1_Platform()}
      set {_platform = newValue}
    }
    /// Returns true if `platform` has been explicitly set.
    var hasPlatform: Bool {self._platform != nil}
    /// Clears the value of `platform`. Subsequent reads from it will return its default value.
    mutating func clearPlatform() {self._platform = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _platform: Cc_Arduino_Cli_Commands_V1_Platform? = nil
  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformSearchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Keywords for the search.
  var searchArgs: String = String()

  /// Whether to show manually installed platforms. `false` causes to skip
  /// manually installed platforms.
  var manuallyInstalled: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_PlatformSearchResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Results of the search.
  var searchOutput: [Cc_Arduino_Cli_Commands_V1_PlatformSummary] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "cc.arduino.cli.commands.v1"

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformInstallRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformInstallRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{3}platform_package\0\u{1}architecture\0\u{1}version\0\u{3}skip_post_install\0\u{3}no_overwrite\0\u{3}skip_pre_uninstall\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.platformPackage) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.architecture) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.skipPostInstall) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.noOverwrite) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.skipPreUninstall) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.platformPackage.isEmpty {
      try visitor.visitSingularStringField(value: self.platformPackage, fieldNumber: 2)
    }
    if !self.architecture.isEmpty {
      try visitor.visitSingularStringField(value: self.architecture, fieldNumber: 3)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 4)
    }
    if self.skipPostInstall != false {
      try visitor.visitSingularBoolField(value: self.skipPostInstall, fieldNumber: 5)
    }
    if self.noOverwrite != false {
      try visitor.visitSingularBoolField(value: self.noOverwrite, fieldNumber: 6)
    }
    if self.skipPreUninstall != false {
      try visitor.visitSingularBoolField(value: self.skipPreUninstall, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformInstallRequest, rhs: Cc_Arduino_Cli_Commands_V1_PlatformInstallRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.platformPackage != rhs.platformPackage {return false}
    if lhs.architecture != rhs.architecture {return false}
    if lhs.version != rhs.version {return false}
    if lhs.skipPostInstall != rhs.skipPostInstall {return false}
    if lhs.noOverwrite != rhs.noOverwrite {return false}
    if lhs.skipPreUninstall != rhs.skipPreUninstall {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformInstallResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}progress\0\u{3}task_progress\0\u{1}result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Cc_Arduino_Cli_Commands_V1_DownloadProgress?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .progress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .progress(v)
        }
      }()
      case 2: try {
        var v: Cc_Arduino_Cli_Commands_V1_TaskProgress?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .taskProgress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .taskProgress(v)
        }
      }()
      case 3: try {
        var v: Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.Result?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .result(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .result(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .progress?: try {
      guard case .progress(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .taskProgress?: try {
      guard case .taskProgress(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .result?: try {
      guard case .result(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse, rhs: Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.Result: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.protoMessageName + ".Result"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.Result, rhs: Cc_Arduino_Cli_Commands_V1_PlatformInstallResponse.Result) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformLoadingError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformLoadingError"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformLoadingError, rhs: Cc_Arduino_Cli_Commands_V1_PlatformLoadingError) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformDownloadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformDownloadRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{3}platform_package\0\u{1}architecture\0\u{1}version\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.platformPackage) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.architecture) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.version) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.platformPackage.isEmpty {
      try visitor.visitSingularStringField(value: self.platformPackage, fieldNumber: 2)
    }
    if !self.architecture.isEmpty {
      try visitor.visitSingularStringField(value: self.architecture, fieldNumber: 3)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformDownloadRequest, rhs: Cc_Arduino_Cli_Commands_V1_PlatformDownloadRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.platformPackage != rhs.platformPackage {return false}
    if lhs.architecture != rhs.architecture {return false}
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformDownloadResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}progress\0\u{1}result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Cc_Arduino_Cli_Commands_V1_DownloadProgress?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .progress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .progress(v)
        }
      }()
      case 2: try {
        var v: Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.Result?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .result(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .result(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .progress?: try {
      guard case .progress(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .result?: try {
      guard case .result(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse, rhs: Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.Result: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.protoMessageName + ".Result"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.Result, rhs: Cc_Arduino_Cli_Commands_V1_PlatformDownloadResponse.Result) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformUninstallRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformUninstallRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{3}platform_package\0\u{1}architecture\0\u{3}skip_pre_uninstall\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.platformPackage) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.architecture) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.skipPreUninstall) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.platformPackage.isEmpty {
      try visitor.visitSingularStringField(value: self.platformPackage, fieldNumber: 2)
    }
    if !self.architecture.isEmpty {
      try visitor.visitSingularStringField(value: self.architecture, fieldNumber: 3)
    }
    if self.skipPreUninstall != false {
      try visitor.visitSingularBoolField(value: self.skipPreUninstall, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformUninstallRequest, rhs: Cc_Arduino_Cli_Commands_V1_PlatformUninstallRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.platformPackage != rhs.platformPackage {return false}
    if lhs.architecture != rhs.architecture {return false}
    if lhs.skipPreUninstall != rhs.skipPreUninstall {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformUninstallResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}task_progress\0\u{1}result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Cc_Arduino_Cli_Commands_V1_TaskProgress?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .taskProgress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .taskProgress(v)
        }
      }()
      case 2: try {
        var v: Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.Result?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .result(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .result(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .taskProgress?: try {
      guard case .taskProgress(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .result?: try {
      guard case .result(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse, rhs: Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.Result: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.protoMessageName + ".Result"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.Result, rhs: Cc_Arduino_Cli_Commands_V1_PlatformUninstallResponse.Result) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_AlreadyAtLatestVersionError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AlreadyAtLatestVersionError"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_AlreadyAtLatestVersionError, rhs: Cc_Arduino_Cli_Commands_V1_AlreadyAtLatestVersionError) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformUpgradeRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformUpgradeRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{3}platform_package\0\u{1}architecture\0\u{3}skip_post_install\0\u{3}skip_pre_uninstall\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.platformPackage) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.architecture) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.skipPostInstall) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.skipPreUninstall) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.platformPackage.isEmpty {
      try visitor.visitSingularStringField(value: self.platformPackage, fieldNumber: 2)
    }
    if !self.architecture.isEmpty {
      try visitor.visitSingularStringField(value: self.architecture, fieldNumber: 3)
    }
    if self.skipPostInstall != false {
      try visitor.visitSingularBoolField(value: self.skipPostInstall, fieldNumber: 4)
    }
    if self.skipPreUninstall != false {
      try visitor.visitSingularBoolField(value: self.skipPreUninstall, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeRequest, rhs: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.platformPackage != rhs.platformPackage {return false}
    if lhs.architecture != rhs.architecture {return false}
    if lhs.skipPostInstall != rhs.skipPostInstall {return false}
    if lhs.skipPreUninstall != rhs.skipPreUninstall {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformUpgradeResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}progress\0\u{3}task_progress\0\u{1}result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Cc_Arduino_Cli_Commands_V1_DownloadProgress?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .progress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .progress(v)
        }
      }()
      case 2: try {
        var v: Cc_Arduino_Cli_Commands_V1_TaskProgress?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .taskProgress(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .taskProgress(v)
        }
      }()
      case 3: try {
        var v: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.Result?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .result(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .result(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .progress?: try {
      guard case .progress(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .taskProgress?: try {
      guard case .taskProgress(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .result?: try {
      guard case .result(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse, rhs: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.Result: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.protoMessageName + ".Result"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}platform\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._platform) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._platform {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.Result, rhs: Cc_Arduino_Cli_Commands_V1_PlatformUpgradeResponse.Result) -> Bool {
    if lhs._platform != rhs._platform {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformSearchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformSearchRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{3}search_args\0\u{3}manually_installed\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.searchArgs) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.manuallyInstalled) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.searchArgs.isEmpty {
      try visitor.visitSingularStringField(value: self.searchArgs, fieldNumber: 2)
    }
    if self.manuallyInstalled != false {
      try visitor.visitSingularBoolField(value: self.manuallyInstalled, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformSearchRequest, rhs: Cc_Arduino_Cli_Commands_V1_PlatformSearchRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.searchArgs != rhs.searchArgs {return false}
    if lhs.manuallyInstalled != rhs.manuallyInstalled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_PlatformSearchResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PlatformSearchResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}search_output\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.searchOutput) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.searchOutput.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.searchOutput, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_PlatformSearchResponse, rhs: Cc_Arduino_Cli_Commands_V1_PlatformSearchResponse) -> Bool {
    if lhs.searchOutput != rhs.searchOutput {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
