// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cc/arduino/cli/commands/v1/upload.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This file is part of arduino-cli.
//
// Copyright 2024 ARDUINO SA (https://www.arduino.cc/)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_UploadRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_storage._instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_uniqueStorage()._instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {_storage._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {_uniqueStorage()._instance = nil}

  /// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
  /// If this field is not defined, the FQBN of the board attached to the sketch
  /// via the `BoardAttach` method is used.
  var fqbn: String {
    get {_storage._fqbn}
    set {_uniqueStorage()._fqbn = newValue}
  }

  /// Path where the sketch to be uploaded is stored. Unless the `import_file`
  /// field is defined, the compiled binary is assumed to be at the location and
  /// filename under this path where it is saved by the `Compile` method.
  var sketchPath: String {
    get {_storage._sketchPath}
    set {_uniqueStorage()._sketchPath = newValue}
  }

  /// The port of the board.
  var port: Cc_Arduino_Cli_Commands_V1_Port {
    get {_storage._port ?? Cc_Arduino_Cli_Commands_V1_Port()}
    set {_uniqueStorage()._port = newValue}
  }
  /// Returns true if `port` has been explicitly set.
  var hasPort: Bool {_storage._port != nil}
  /// Clears the value of `port`. Subsequent reads from it will return its default value.
  mutating func clearPort() {_uniqueStorage()._port = nil}

  /// Whether to turn on verbose output during the upload.
  var verbose: Bool {
    get {_storage._verbose}
    set {_uniqueStorage()._verbose = newValue}
  }

  /// After upload, verify that the contents of the memory on the board match the
  /// uploaded binary.
  var verify: Bool {
    get {_storage._verify}
    set {_uniqueStorage()._verify = newValue}
  }

  /// When `import_file` is specified, it overrides the `import_dir` and
  /// `sketch_path` params.
  var importFile: String {
    get {_storage._importFile}
    set {_uniqueStorage()._importFile = newValue}
  }

  /// Custom path to a directory containing compiled files. When `import_dir` is
  /// not specified, the standard build directory under `sketch_path` is used.
  var importDir: String {
    get {_storage._importDir}
    set {_uniqueStorage()._importDir = newValue}
  }

  /// The programmer to use for upload. If set an UploadUsingProgrammer is
  /// triggered instead of a normal upload. The UploadUsingProgrammer call may
  /// also be used for explicit error check.
  var programmer: String {
    get {_storage._programmer}
    set {_uniqueStorage()._programmer = newValue}
  }

  /// If set to true, the actual upload will not be performed but a trace output
  /// will be printed stdout. This is for debugging purposes.
  var dryRun: Bool {
    get {_storage._dryRun}
    set {_uniqueStorage()._dryRun = newValue}
  }

  /// User provided fields usually used by upload tools that need authentication
  /// or in any case fields that can be customized by the user at upload time
  /// and cannot be known previously.
  /// For more info:
  /// https://arduino.github.io/arduino-cli/latest/platform-specification/#user-provided-fields
  var userFields: Dictionary<String,String> {
    get {_storage._userFields}
    set {_uniqueStorage()._userFields = newValue}
  }

  /// List of custom upload properties.
  var uploadProperties: [String] {
    get {_storage._uploadProperties}
    set {_uniqueStorage()._uploadProperties = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_UploadResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_UploadResponse.OneOf_Message? = nil

  /// The output of the upload process.
  var outStream: Data {
    get {
      if case .outStream(let v)? = message {return v}
      return Data()
    }
    set {message = .outStream(newValue)}
  }

  /// The error output of the upload process.
  var errStream: Data {
    get {
      if case .errStream(let v)? = message {return v}
      return Data()
    }
    set {message = .errStream(newValue)}
  }

  /// The upload result.
  var result: Cc_Arduino_Cli_Commands_V1_UploadResult {
    get {
      if case .result(let v)? = message {return v}
      return Cc_Arduino_Cli_Commands_V1_UploadResult()
    }
    set {message = .result(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// The output of the upload process.
    case outStream(Data)
    /// The error output of the upload process.
    case errStream(Data)
    /// The upload result.
    case result(Cc_Arduino_Cli_Commands_V1_UploadResult)

  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_UploadResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// When a board requires a port disconnection to perform the upload, this
  /// field returns the port where the board reconnects after the upload.
  var updatedUploadPort: Cc_Arduino_Cli_Commands_V1_Port {
    get {_updatedUploadPort ?? Cc_Arduino_Cli_Commands_V1_Port()}
    set {_updatedUploadPort = newValue}
  }
  /// Returns true if `updatedUploadPort` has been explicitly set.
  var hasUpdatedUploadPort: Bool {self._updatedUploadPort != nil}
  /// Clears the value of `updatedUploadPort`. Subsequent reads from it will return its default value.
  mutating func clearUpdatedUploadPort() {self._updatedUploadPort = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _updatedUploadPort: Cc_Arduino_Cli_Commands_V1_Port? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ProgrammerIsRequiredForUploadError: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_storage._instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_uniqueStorage()._instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {_storage._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {_uniqueStorage()._instance = nil}

  /// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
  /// If this field is not defined, the FQBN of the board attached to the sketch
  /// via the `BoardAttach` method is used.
  var fqbn: String {
    get {_storage._fqbn}
    set {_uniqueStorage()._fqbn = newValue}
  }

  /// Path where the sketch to be uploaded is stored. Unless the `import_file`
  /// field is defined, the compiled binary is assumed to be at the location and
  /// filename under this path where it is saved by the `Compile` method.
  var sketchPath: String {
    get {_storage._sketchPath}
    set {_uniqueStorage()._sketchPath = newValue}
  }

  /// The port of the board.
  var port: Cc_Arduino_Cli_Commands_V1_Port {
    get {_storage._port ?? Cc_Arduino_Cli_Commands_V1_Port()}
    set {_uniqueStorage()._port = newValue}
  }
  /// Returns true if `port` has been explicitly set.
  var hasPort: Bool {_storage._port != nil}
  /// Clears the value of `port`. Subsequent reads from it will return its default value.
  mutating func clearPort() {_uniqueStorage()._port = nil}

  /// Whether to turn on verbose output during the upload.
  var verbose: Bool {
    get {_storage._verbose}
    set {_uniqueStorage()._verbose = newValue}
  }

  /// After upload, verify that the contents of the memory on the board match the
  /// uploaded binary.
  var verify: Bool {
    get {_storage._verify}
    set {_uniqueStorage()._verify = newValue}
  }

  /// When `import_file` is specified, it overrides the `import_dir` and
  /// `sketch_path` params.
  var importFile: String {
    get {_storage._importFile}
    set {_uniqueStorage()._importFile = newValue}
  }

  /// Custom path to a directory containing compiled files. When `import_dir` is
  /// not specified, the standard build directory under `sketch_path` is used.
  var importDir: String {
    get {_storage._importDir}
    set {_uniqueStorage()._importDir = newValue}
  }

  /// The programmer to use for upload.
  var programmer: String {
    get {_storage._programmer}
    set {_uniqueStorage()._programmer = newValue}
  }

  /// If set to true, the actual upload will not be performed but a trace output
  /// will be printed stdout. This is for debugging purposes.
  var dryRun: Bool {
    get {_storage._dryRun}
    set {_uniqueStorage()._dryRun = newValue}
  }

  /// User provided fields usually used by upload tools that need authentication
  /// or in any case fields that can be customized by the user at upload time
  /// and cannot be known previously.
  /// For more info:
  /// https://arduino.github.io/arduino-cli/latest/platform-specification/#user-provided-fields
  var userFields: Dictionary<String,String> {
    get {_storage._userFields}
    set {_uniqueStorage()._userFields = newValue}
  }

  /// List of custom upload properties.
  var uploadProperties: [String] {
    get {_storage._uploadProperties}
    set {_uniqueStorage()._uploadProperties = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerResponse.OneOf_Message? = nil

  /// The output of the upload process.
  var outStream: Data {
    get {
      if case .outStream(let v)? = message {return v}
      return Data()
    }
    set {message = .outStream(newValue)}
  }

  /// The error output of the upload process.
  var errStream: Data {
    get {
      if case .errStream(let v)? = message {return v}
      return Data()
    }
    set {message = .errStream(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// The output of the upload process.
    case outStream(Data)
    /// The error output of the upload process.
    case errStream(Data)

  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BurnBootloaderRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
  var fqbn: String = String()

  /// The port of the programmer used to program the bootloader.
  var port: Cc_Arduino_Cli_Commands_V1_Port {
    get {_port ?? Cc_Arduino_Cli_Commands_V1_Port()}
    set {_port = newValue}
  }
  /// Returns true if `port` has been explicitly set.
  var hasPort: Bool {self._port != nil}
  /// Clears the value of `port`. Subsequent reads from it will return its default value.
  mutating func clearPort() {self._port = nil}

  /// Whether to turn on verbose output during the programming.
  var verbose: Bool = false

  /// After programming, verify the contents of the memory on the board match the
  /// uploaded binary.
  var verify: Bool = false

  /// The programmer to use for burning bootloader.
  var programmer: String = String()

  /// If set to true, the actual upload will not be performed but a trace output
  /// will be printed stdout. This is for debugging purposes.
  var dryRun: Bool = false

  /// User provided fields usually used by upload tools that need authentication
  /// or in any case fields that can be customized by the user at upload time
  /// and cannot be known previously.
  /// For more info:
  /// https://arduino.github.io/arduino-cli/latest/platform-specification/#user-provided-fields
  var userFields: Dictionary<String,String> = [:]

  /// List of custom upload properties.
  var uploadProperties: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
  fileprivate var _port: Cc_Arduino_Cli_Commands_V1_Port? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_BurnBootloaderResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var message: Cc_Arduino_Cli_Commands_V1_BurnBootloaderResponse.OneOf_Message? = nil

  /// The output of the burn bootloader process.
  var outStream: Data {
    get {
      if case .outStream(let v)? = message {return v}
      return Data()
    }
    set {message = .outStream(newValue)}
  }

  /// The error output of the burn bootloader process.
  var errStream: Data {
    get {
      if case .errStream(let v)? = message {return v}
      return Data()
    }
    set {message = .errStream(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Message: Equatable, Sendable {
    /// The output of the burn bootloader process.
    case outStream(Data)
    /// The error output of the burn bootloader process.
    case errStream(Data)

  }

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ListProgrammersAvailableForUploadRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
  var fqbn: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_ListProgrammersAvailableForUploadResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of programmers supported by the board.
  var programmers: [Cc_Arduino_Cli_Commands_V1_Programmer] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SupportedUserFieldsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Arduino Core Service instance from the `Init` response.
  var instance: Cc_Arduino_Cli_Commands_V1_Instance {
    get {_instance ?? Cc_Arduino_Cli_Commands_V1_Instance()}
    set {_instance = newValue}
  }
  /// Returns true if `instance` has been explicitly set.
  var hasInstance: Bool {self._instance != nil}
  /// Clears the value of `instance`. Subsequent reads from it will return its default value.
  mutating func clearInstance() {self._instance = nil}

  /// Fully qualified board name of the target board (e.g., `arduino:avr:uno`).
  var fqbn: String = String()

  /// Protocol that will be used to upload, this information is
  /// necessary to pick the right upload tool for the board specified
  /// with the FQBN.
  var `protocol`: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_UserField: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Id of the tool that supports this field.
  var toolID: String = String()

  /// Name used internally to store and retrieve this field.
  var name: String = String()

  /// Label is the text shown to the user when they need to input this field.
  var label: String = String()

  /// True if the value of the field must not be shown when typing, for example
  /// when the user inputs a network password.
  var secret: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Cc_Arduino_Cli_Commands_V1_SupportedUserFieldsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// User fields supported by board specified in SupportedUserFieldsRequest.
  /// If board doesn't support any field it will be empty.
  var userFields: [Cc_Arduino_Cli_Commands_V1_UserField] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "cc.arduino.cli.commands.v1"

nonisolated extension Cc_Arduino_Cli_Commands_V1_UploadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UploadRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0\u{3}sketch_path\0\u{1}port\0\u{1}verbose\0\u{1}verify\0\u{3}import_file\0\u{3}import_dir\0\u{1}programmer\0\u{3}dry_run\0\u{3}user_fields\0\u{3}upload_properties\0")

  fileprivate class _StorageClass {
    var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
    var _fqbn: String = String()
    var _sketchPath: String = String()
    var _port: Cc_Arduino_Cli_Commands_V1_Port? = nil
    var _verbose: Bool = false
    var _verify: Bool = false
    var _importFile: String = String()
    var _importDir: String = String()
    var _programmer: String = String()
    var _dryRun: Bool = false
    var _userFields: Dictionary<String,String> = [:]
    var _uploadProperties: [String] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _instance = source._instance
      _fqbn = source._fqbn
      _sketchPath = source._sketchPath
      _port = source._port
      _verbose = source._verbose
      _verify = source._verify
      _importFile = source._importFile
      _importDir = source._importDir
      _programmer = source._programmer
      _dryRun = source._dryRun
      _userFields = source._userFields
      _uploadProperties = source._uploadProperties
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._instance) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._fqbn) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._sketchPath) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._port) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._verbose) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._verify) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._importFile) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._importDir) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._programmer) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._dryRun) }()
        case 11: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._userFields) }()
        case 12: try { try decoder.decodeRepeatedStringField(value: &_storage._uploadProperties) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._instance {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._fqbn.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fqbn, fieldNumber: 2)
      }
      if !_storage._sketchPath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._sketchPath, fieldNumber: 3)
      }
      try { if let v = _storage._port {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      if _storage._verbose != false {
        try visitor.visitSingularBoolField(value: _storage._verbose, fieldNumber: 5)
      }
      if _storage._verify != false {
        try visitor.visitSingularBoolField(value: _storage._verify, fieldNumber: 6)
      }
      if !_storage._importFile.isEmpty {
        try visitor.visitSingularStringField(value: _storage._importFile, fieldNumber: 7)
      }
      if !_storage._importDir.isEmpty {
        try visitor.visitSingularStringField(value: _storage._importDir, fieldNumber: 8)
      }
      if !_storage._programmer.isEmpty {
        try visitor.visitSingularStringField(value: _storage._programmer, fieldNumber: 9)
      }
      if _storage._dryRun != false {
        try visitor.visitSingularBoolField(value: _storage._dryRun, fieldNumber: 10)
      }
      if !_storage._userFields.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._userFields, fieldNumber: 11)
      }
      if !_storage._uploadProperties.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._uploadProperties, fieldNumber: 12)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_UploadRequest, rhs: Cc_Arduino_Cli_Commands_V1_UploadRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._instance != rhs_storage._instance {return false}
        if _storage._fqbn != rhs_storage._fqbn {return false}
        if _storage._sketchPath != rhs_storage._sketchPath {return false}
        if _storage._port != rhs_storage._port {return false}
        if _storage._verbose != rhs_storage._verbose {return false}
        if _storage._verify != rhs_storage._verify {return false}
        if _storage._importFile != rhs_storage._importFile {return false}
        if _storage._importDir != rhs_storage._importDir {return false}
        if _storage._programmer != rhs_storage._programmer {return false}
        if _storage._dryRun != rhs_storage._dryRun {return false}
        if _storage._userFields != rhs_storage._userFields {return false}
        if _storage._uploadProperties != rhs_storage._uploadProperties {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_UploadResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UploadResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}out_stream\0\u{3}err_stream\0\u{1}result\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .outStream(v)
        }
      }()
      case 2: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .errStream(v)
        }
      }()
      case 3: try {
        var v: Cc_Arduino_Cli_Commands_V1_UploadResult?
        var hadOneofValue = false
        if let current = self.message {
          hadOneofValue = true
          if case .result(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.message = .result(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .outStream?: try {
      guard case .outStream(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    }()
    case .errStream?: try {
      guard case .errStream(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    }()
    case .result?: try {
      guard case .result(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_UploadResponse, rhs: Cc_Arduino_Cli_Commands_V1_UploadResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_UploadResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UploadResult"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}updated_upload_port\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._updatedUploadPort) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._updatedUploadPort {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_UploadResult, rhs: Cc_Arduino_Cli_Commands_V1_UploadResult) -> Bool {
    if lhs._updatedUploadPort != rhs._updatedUploadPort {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ProgrammerIsRequiredForUploadError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProgrammerIsRequiredForUploadError"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ProgrammerIsRequiredForUploadError, rhs: Cc_Arduino_Cli_Commands_V1_ProgrammerIsRequiredForUploadError) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UploadUsingProgrammerRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0\u{3}sketch_path\0\u{1}port\0\u{1}verbose\0\u{1}verify\0\u{3}import_file\0\u{3}import_dir\0\u{1}programmer\0\u{3}dry_run\0\u{3}user_fields\0\u{3}upload_properties\0")

  fileprivate class _StorageClass {
    var _instance: Cc_Arduino_Cli_Commands_V1_Instance? = nil
    var _fqbn: String = String()
    var _sketchPath: String = String()
    var _port: Cc_Arduino_Cli_Commands_V1_Port? = nil
    var _verbose: Bool = false
    var _verify: Bool = false
    var _importFile: String = String()
    var _importDir: String = String()
    var _programmer: String = String()
    var _dryRun: Bool = false
    var _userFields: Dictionary<String,String> = [:]
    var _uploadProperties: [String] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _instance = source._instance
      _fqbn = source._fqbn
      _sketchPath = source._sketchPath
      _port = source._port
      _verbose = source._verbose
      _verify = source._verify
      _importFile = source._importFile
      _importDir = source._importDir
      _programmer = source._programmer
      _dryRun = source._dryRun
      _userFields = source._userFields
      _uploadProperties = source._uploadProperties
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._instance) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._fqbn) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._sketchPath) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._port) }()
        case 5: try { try decoder.decodeSingularBoolField(value: &_storage._verbose) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._verify) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._importFile) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._importDir) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._programmer) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._dryRun) }()
        case 11: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._userFields) }()
        case 12: try { try decoder.decodeRepeatedStringField(value: &_storage._uploadProperties) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._instance {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._fqbn.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fqbn, fieldNumber: 2)
      }
      if !_storage._sketchPath.isEmpty {
        try visitor.visitSingularStringField(value: _storage._sketchPath, fieldNumber: 3)
      }
      try { if let v = _storage._port {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      if _storage._verbose != false {
        try visitor.visitSingularBoolField(value: _storage._verbose, fieldNumber: 5)
      }
      if _storage._verify != false {
        try visitor.visitSingularBoolField(value: _storage._verify, fieldNumber: 6)
      }
      if !_storage._importFile.isEmpty {
        try visitor.visitSingularStringField(value: _storage._importFile, fieldNumber: 7)
      }
      if !_storage._importDir.isEmpty {
        try visitor.visitSingularStringField(value: _storage._importDir, fieldNumber: 8)
      }
      if !_storage._programmer.isEmpty {
        try visitor.visitSingularStringField(value: _storage._programmer, fieldNumber: 9)
      }
      if _storage._dryRun != false {
        try visitor.visitSingularBoolField(value: _storage._dryRun, fieldNumber: 10)
      }
      if !_storage._userFields.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._userFields, fieldNumber: 11)
      }
      if !_storage._uploadProperties.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._uploadProperties, fieldNumber: 12)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerRequest, rhs: Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._instance != rhs_storage._instance {return false}
        if _storage._fqbn != rhs_storage._fqbn {return false}
        if _storage._sketchPath != rhs_storage._sketchPath {return false}
        if _storage._port != rhs_storage._port {return false}
        if _storage._verbose != rhs_storage._verbose {return false}
        if _storage._verify != rhs_storage._verify {return false}
        if _storage._importFile != rhs_storage._importFile {return false}
        if _storage._importDir != rhs_storage._importDir {return false}
        if _storage._programmer != rhs_storage._programmer {return false}
        if _storage._dryRun != rhs_storage._dryRun {return false}
        if _storage._userFields != rhs_storage._userFields {return false}
        if _storage._uploadProperties != rhs_storage._uploadProperties {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UploadUsingProgrammerResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}out_stream\0\u{3}err_stream\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .outStream(v)
        }
      }()
      case 2: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .errStream(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .outStream?: try {
      guard case .outStream(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    }()
    case .errStream?: try {
      guard case .errStream(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerResponse, rhs: Cc_Arduino_Cli_Commands_V1_UploadUsingProgrammerResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BurnBootloaderRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BurnBootloaderRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0\u{1}port\0\u{1}verbose\0\u{1}verify\0\u{1}programmer\0\u{3}dry_run\0\u{4}\u{4}user_fields\0\u{3}upload_properties\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._port) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.verbose) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.verify) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.programmer) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.dryRun) }()
      case 11: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.userFields) }()
      case 12: try { try decoder.decodeRepeatedStringField(value: &self.uploadProperties) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 2)
    }
    try { if let v = self._port {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.verbose != false {
      try visitor.visitSingularBoolField(value: self.verbose, fieldNumber: 4)
    }
    if self.verify != false {
      try visitor.visitSingularBoolField(value: self.verify, fieldNumber: 5)
    }
    if !self.programmer.isEmpty {
      try visitor.visitSingularStringField(value: self.programmer, fieldNumber: 6)
    }
    if self.dryRun != false {
      try visitor.visitSingularBoolField(value: self.dryRun, fieldNumber: 7)
    }
    if !self.userFields.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.userFields, fieldNumber: 11)
    }
    if !self.uploadProperties.isEmpty {
      try visitor.visitRepeatedStringField(value: self.uploadProperties, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BurnBootloaderRequest, rhs: Cc_Arduino_Cli_Commands_V1_BurnBootloaderRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs._port != rhs._port {return false}
    if lhs.verbose != rhs.verbose {return false}
    if lhs.verify != rhs.verify {return false}
    if lhs.programmer != rhs.programmer {return false}
    if lhs.dryRun != rhs.dryRun {return false}
    if lhs.userFields != rhs.userFields {return false}
    if lhs.uploadProperties != rhs.uploadProperties {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_BurnBootloaderResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BurnBootloaderResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}out_stream\0\u{3}err_stream\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .outStream(v)
        }
      }()
      case 2: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.message != nil {try decoder.handleConflictingOneOf()}
          self.message = .errStream(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.message {
    case .outStream?: try {
      guard case .outStream(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    }()
    case .errStream?: try {
      guard case .errStream(let v)? = self.message else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_BurnBootloaderResponse, rhs: Cc_Arduino_Cli_Commands_V1_BurnBootloaderResponse) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ListProgrammersAvailableForUploadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ListProgrammersAvailableForUploadRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ListProgrammersAvailableForUploadRequest, rhs: Cc_Arduino_Cli_Commands_V1_ListProgrammersAvailableForUploadRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_ListProgrammersAvailableForUploadResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ListProgrammersAvailableForUploadResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}programmers\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.programmers) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.programmers.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.programmers, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_ListProgrammersAvailableForUploadResponse, rhs: Cc_Arduino_Cli_Commands_V1_ListProgrammersAvailableForUploadResponse) -> Bool {
    if lhs.programmers != rhs.programmers {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SupportedUserFieldsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SupportedUserFieldsRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}instance\0\u{1}fqbn\0\u{1}protocol\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._instance) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fqbn) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.`protocol`) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._instance {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.fqbn.isEmpty {
      try visitor.visitSingularStringField(value: self.fqbn, fieldNumber: 2)
    }
    if !self.`protocol`.isEmpty {
      try visitor.visitSingularStringField(value: self.`protocol`, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SupportedUserFieldsRequest, rhs: Cc_Arduino_Cli_Commands_V1_SupportedUserFieldsRequest) -> Bool {
    if lhs._instance != rhs._instance {return false}
    if lhs.fqbn != rhs.fqbn {return false}
    if lhs.`protocol` != rhs.`protocol` {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_UserField: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserField"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}tool_id\0\u{1}name\0\u{1}label\0\u{1}secret\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.toolID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.secret) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.toolID.isEmpty {
      try visitor.visitSingularStringField(value: self.toolID, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 3)
    }
    if self.secret != false {
      try visitor.visitSingularBoolField(value: self.secret, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_UserField, rhs: Cc_Arduino_Cli_Commands_V1_UserField) -> Bool {
    if lhs.toolID != rhs.toolID {return false}
    if lhs.name != rhs.name {return false}
    if lhs.label != rhs.label {return false}
    if lhs.secret != rhs.secret {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Cc_Arduino_Cli_Commands_V1_SupportedUserFieldsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SupportedUserFieldsResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}user_fields\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.userFields) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userFields.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.userFields, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Cc_Arduino_Cli_Commands_V1_SupportedUserFieldsResponse, rhs: Cc_Arduino_Cli_Commands_V1_SupportedUserFieldsResponse) -> Bool {
    if lhs.userFields != rhs.userFields {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
